In [1]:
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import numpy as np
import deeptime as dpt
%matplotlib qt   
# doesn't work on my laptop

from tistools import read_inputfile, get_LMR_interfaces, read_pathensemble, get_weights
from tistools import set_tau_distrib, set_tau_first_hit_M_distrib, cross_dist_distr, pathlength_distr
from tistools import ACCFLAGS, REJFLAGS

from tistools import get_lmr_masks, get_generation_mask, get_flag_mask, select_with_masks
from tistools import unwrap_by_weight, running_avg_local_probs, get_local_probs, get_global_probs_from_dict, get_global_probs_from_local
from tistools import make_plot_trajs

from pprint import pprint    # to print the vars of the pathensemble object

# TODO: change to istar_analysis when finished
# from istar_test import *
from tistools import global_pcross_msm_star, construct_M_istar, get_transition_probs_weights, get_transition_probs_interm, get_simple_probs, get_summed_probs
from tistools import get_weights_staple, compute_weight_matrices, compute_weight_matrix, plot_rv_star, plot_rv_repptis, plot_rv_comp
from tistools import display_data, memory_analysis, ploc_memory, plot_memory_analysis, pcca_analysis, cprobs_repptis_istar, ploc_repptis_from_staples, generate_state_labels, visualize_turn_based_analysis, analyze_memory_vs_free_energy_effects, analyze_momentum_vs_free_energy


%matplotlib qt

/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/APPTIS/tistools/lib/istar_analysis.py:1314: SyntaxWarning: invalid escape sequence '\l'
  ax.set_xlabel("Position x (=$\lambda$)")


In [2]:
import logging

logger = logging.getLogger(__name__)

In [3]:
%autoreload 2   
# something with pip install -e .

# Reading

In [4]:
# zero_minus_one = True if lambda_-1 interface is set
# zero_minus_one = False if lambda_-1 interface is not set

# data the maze
# ---------------
# indir = indir = "/run/user/1001/gvfs/smb-share:server=files.ugent.be,share=eliawils,user=eliawils/shares/tw06_biommeda_pastime1/11.2024_StapleTIS/simulations/flat/sim_istar0br2108/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istar2cosbr_2108/"
indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_slopeg5_2702/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istar0t/"

# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarwell2_2108/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarwell250k_0506/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarwell0_0209/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarwell050k_1606/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarwell2_br/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarwell0_add_0502/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarwell0add50k_1606/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarwell0_add_br2305/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istar0br10intf/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istar0br6dintf/"
# indir = "/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istar0br15dintf/"
# indir = "/mnt/tw06_biommeda_pastime1/11.2024_StapleTIS/simulations/maze2D/sim_istarmaze_kick2708/"
# indir = "/mnt/tw06_biommeda_pastime1/11.2024_StapleTIS/simulations/maze2D/sim_/"
zero_minus_one = False
inputfile = indir + "logging.log"


import os
import glob
os.chdir(indir)
print(os.getcwd())

folders = glob.glob(indir + "/0[0-9][0-9]")
folders = sorted(folders)
print(folders)

/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5
['/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/000', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/001', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/002', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/003', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/004', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/005', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/006', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/007', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/008', '/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DAT

In [5]:
# !!! last lines !!!  allow to speed up this notebook
# pe.set_orders(load=False...)  -> 1st time you run the code, this will store npy files
# pe.set_orders(load=True...)  -> next time you run the code, you can read npy files

# Reading all input
#===================
interfaces, zero_left, timestep = read_inputfile(inputfile)
LMR_interfaces, LMR_strings = get_LMR_interfaces(interfaces, zero_left)
pathensembles = []
for i,fol in enumerate(folders):
    print("#"*80)
    print(fol)
    pe = read_pathensemble(fol+"/pathensemble.txt")
    pe.set_name(fol)
    pe.set_interfaces([LMR_interfaces[i], LMR_strings[i]])
    if i==0:
        pe.set_zero_minus_one(zero_minus_one)   # TODO this is never used
        pe.set_in_zero_minus(True)
    if i==1:
        pe.set_in_zero_plus(True)
    w, _ = get_weights(pe.flags, ACCFLAGS, REJFLAGS, verbose = False)
    pe.set_weights(w)
    print("pathensemble info: ")
    pprint(vars(pe))
    pathensembles.append(pe)
    # read order parameters order.txt/order.npy into path ensemble object
    #pe.set_orders(load=False, acc_only=True, save=False) # if saving doesn't work
    #### CHANGE HERE ####
    # pe.set_orders(load=False, acc_only=True, save=True) # for the 1st time
    # pe.set_orders(load=True, acc_only=True) # for the next times, save=True/False is not important

################################################################################
/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/PyRETIS3/toytis/simulations/sim_istarz_g5/000
pathensemble info: 
{'cyclenumbers': array([     0,      1,      2, ...,  99998,  99999, 100000]),
 'dirs': array([-1.,  1.,  1., ...,  1., -1., -1.]),
 'flags': array(['ACC', 'BTL', 'BTL', ..., 'ACC', 'FTL', 'FTL'], dtype='<U3'),
 'generation': array(['ld', 'sh', 'sh', ..., 'sh', 'sh', 'sh'], dtype='<U2'),
 'has_zero_minus_one': False,
 'in_zero_minus': True,
 'in_zero_plus': False,
 'interfaces': [[0.05, 0.05, 0.05], ['l_[0]', 'l_[0]', 'l_[0]']],
 'istar_idx': array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]]),
 'lambmaxs': array([0.05026212, 0.02820185, 0.0331673 , ..., 0.05009164, 0.05011043,
       0.05063254]),
 'lambmins': array([-0.00493005, -0.00379134, -0.00368015, ..., -0.00320428,
       -0.00745263, -0.00268888]),
 'lengths': array([ 295,  353,  415, 

In [6]:
for pe in pathensembles:
    print(f"ensemble {pathensembles.index(pe)}")
    print(max(pe.lengths))

for i in range(len(pathensembles)):
    accmask = get_flag_mask(pathensembles[i], "ACC")
    loadmask = get_generation_mask(pathensembles[i], "ld")
    mask = get_lmr_masks(pathensembles[i])
    print(i, np.average(select_with_masks(pathensembles[i].lengths, [~loadmask, accmask])))
    print("LMRlen", i, np.average(select_with_masks(pathensembles[i].lengths, [~loadmask, accmask])))

ensemble 0
7370
ensemble 1
8383
ensemble 2
8383
ensemble 3
7339
ensemble 4
8113
ensemble 5
8501
ensemble 6
9202
ensemble 7
9324
ensemble 8
8596
ensemble 9
9267
ensemble 10
9187
0 789.1265349258539
LMRlen 0 789.1265349258539
1 180.12012991720678
LMRlen 1 180.12012991720678
2 1324.0081090372287
LMRlen 2 1324.0081090372287
3 1628.446435134142
LMRlen 3 1628.446435134142
4 1848.0398501362397
LMRlen 4 1848.0398501362397
5 2067.522290699536
LMRlen 5 2067.522290699536
6 2268.728101911798
LMRlen 6 2268.728101911798
7 2303.906652720491
LMRlen 7 2303.906652720491
8 2248.2358733580577
LMRlen 8 2248.2358733580577
9 2125.05311305545
LMRlen 9 2125.05311305545
10 1847.7480229845821
LMRlen 10 1847.7480229845821


In [7]:
# plocrepptis, plocistar = cprobs_repptis_istar(pathensembles, interfaces, len(interfaces))
plocrepptis, plocistar = cprobs_repptis_istar(pathensembles, interfaces, len(interfaces))

weights:
accepted      59613
rejected      40388
omitted       0
total trajs   100001
total weights 100001
Sum weights ensemble 0:  0.0
weights:
accepted      68968
rejected      31033
omitted       0
total trajs   100001
total weights 100001
Sum weights ensemble 1:  99999.0
weights:
accepted      49452
rejected      50549
omitted       0
total trajs   100001
total weights 105010
Sum weights ensemble 2:  130750.0
weights:
accepted      54421
rejected      45580
omitted       0
total trajs   100001
total weights 132542
Sum weights ensemble 3:  132537.0
weights:
accepted      52849
rejected      47152
omitted       0
total trajs   100001
total weights 137930
Sum weights ensemble 4:  137929.0
weights:
accepted      49977
rejected      50024
omitted       0
total trajs   100001
total weights 147644
Sum weights ensemble 5:  147643.0
weights:
accepted      52517
rejected      47484
omitted       0
total trajs   100001
total weights 156416
Sum weights ensemble 6:  156415.0
weights:
accepted  

In [8]:
X, wpath, W = display_data(pathensembles, interfaces, len(interfaces))
p, q = get_transition_probs_weights(wpath)

----------
ENSEMBLE [0-] | ID 0
----------
weights:
accepted      59613
rejected      40388
omitted       0
total trajs   100001
total weights 100001
Sum weights ensemble 0: 0.0000
Sum weights ensemble 0: 0.0000

1a. Raw data: unweighted C matrices
C[0] = 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

1b. Raw data: unweighted path counts with new MD steps
C_md[0] = 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0

In [9]:
ploc_repptis, ploc_istar = ploc_repptis_from_staples(pathensembles, interfaces, len(interfaces)) 
ploctest = [{} for _ in ploc_istar.keys()]
for i in list(ploc_istar.keys())[1:]:
    ploctest[i]["LMR"] = ploc_istar[i]["LMRtot"][0]
    ploctest[i]["LML"] = ploc_istar[i]["LMLtot"][0]
    ploctest[i]["RMR"] = ploc_istar[i]["RMRtot"][0]
    ploctest[i]["RML"] = ploc_istar[i]["RMLtot"][0]

print('istar', get_global_probs_from_dict(ploctest)[-1])

ploctest2 = [{} for _ in ploc_repptis.keys()]
for i in list(ploc_repptis.keys())[1:]:
    ploctest2[i]["LMR"] = ploc_repptis[i]["LMR"]
    ploctest2[i]["LML"] = ploc_repptis[i]["LML"]
    ploctest2[i]["RMR"] = ploc_repptis[i]["RMR"]
    ploctest2[i]["RML"] = ploc_repptis[i]["RML"]
print('repptis', get_global_probs_from_dict(ploctest2)[-1])

weights:
accepted      59613
rejected      40388
omitted       0
total trajs   100001
total weights 100001
Sum weights ensemble 0:  0.0
weights:
accepted      68968
rejected      31033
omitted       0
total trajs   100001
total weights 100001
Sum weights ensemble 1:  99999.0
weights:
accepted      49452
rejected      50549
omitted       0
total trajs   100001
total weights 105010
Sum weights ensemble 2:  130750.0
weights:
accepted      54421
rejected      45580
omitted       0
total trajs   100001
total weights 132542
Sum weights ensemble 3:  132537.0
weights:
accepted      52849
rejected      47152
omitted       0
total trajs   100001
total weights 137930
Sum weights ensemble 4:  137929.0
weights:
accepted      49977
rejected      50024
omitted       0
total trajs   100001
total weights 147644
Sum weights ensemble 5:  147643.0
weights:
accepted      52517
rejected      47484
omitted       0
total trajs   100001
total weights 156416
Sum weights ensemble 6:  156415.0
weights:
accepted  

In [10]:
q_k, q_tot = memory_analysis(wpath, True)
plot_memory_analysis(pathensembles, q_tot, p, interfaces, q_errors=indir + "/block_error_analysis_qstaple_1.txt")
# plot_free_energy_landscape(interfaces, q_tot[0], q_tot[1])


--------------------
ENSEMBLE [0*] | ID 1
--------------------
==== L -> R ====
-> interface 0 is reached, probability to reach interface 1:
    - START at interface 0: 0.05578841788523465 | # weights: 189430.0
-> interface 1 is reached, probability to reach interface 2:
    - START at interface 0: 0.5999242997728993 | # weights: 10568.0
-> interface 2 is reached, probability to reach interface 3:
    - START at interface 0: 0.5430599369085174 | # weights: 6340.0
-> interface 3 is reached, probability to reach interface 4:
    - START at interface 0: 0.44205634620970086 | # weights: 3443.0
-> interface 4 is reached, probability to reach interface 5:
    - START at interface 0: 0.4159001314060447 | # weights: 1522.0
-> interface 5 is reached, probability to reach interface 6:
    - START at interface 0: 0.2717219589257504 | # weights: 633.0
-> interface 6 is reached, probability to reach interface 7:
    - START at interface 0: 0.3081395348837209 | # weights: 172.0
-> interface 7 is rea

(<Figure size 1800x700 with 6 Axes>,
 <Figure size 1800x1200 with 6 Axes>,
 <Figure size 1800x1400 with 3 Axes>)

In [18]:
results = analyze_memory_vs_free_energy_effects(interfaces, q_tot[0], q_tot[1])
visualize_turn_based_analysis(results, interfaces, q_tot[0], q_tot[1])

/mnt/0bf0c339-34bb-4500-a5fb-f3c2a863de29/DATA/APPTIS/tistools/lib/istar_analysis.py:1314: SyntaxWarning: invalid escape sequence '\l'
  ax.set_xlabel("Position x (=$\lambda$)")


TypeError: 'int' object is not subscriptable

In [ ]:
ploc_memory(pathensembles, interfaces, trr=True)

Weights of the different paths:
wRMR = 50000
wRML = 0
wLMR = 0
wLML = 0
Local crossing probabilities:
pRMR = 1.0
pRML = 0.0
pLMR = nan
pLML = nan
Local crossing probabilities:
p2R = 1.0
p2L = 0.0
weights:
accepted      37346
rejected      12655
omitted       0
total trajs   50001
total weights 50001
Sum weights ensemble 0:  0.0
weights:
accepted      28120
rejected      21881
omitted       0
total trajs   50001
total weights 50001
Sum weights ensemble 1:  50000.0

Intermediate transition probabilities (q matrix):
[[1.   0.83]
 [1.   0.  ]]

Final transition probabilities (p matrix):
[[0.17 0.83]
 [1.   0.  ]]

Local crossing probabilities computed successfully
Weights of the different paths:
wRMR = 0
wRML = 22872
wLMR = 22484
wLML = 4644
Local crossing probabilities:
pRMR = 0.0
pRML = 1.0
pLMR = 0.8288115600117959
pLML = 0.17118843998820407
Local crossing probabilities:
p2R = 0.44968
p2L = 0.55032
weights:
accepted      37346
rejected      12655
omitted       0
total trajs   50001
tota

{'mlst': [1.0,
  0.8288115600117959,
  0.22661173920000002,
  0.17571017292544364,
  0.12721703967265813,
  0.09955423087426785],
 'apptis': [1.0,
  0.8300270844008492,
  0.814802195253981,
  0.797357616219812,
  0.6498487453305463,
  0.6392009672310227],
 'repptis': [1.0,
  0.8288115600117959,
  0.8126477390581147,
  0.7923829783001795,
  0.5617787867610236,
  0.5509082089540307]}

In [ ]:
M = construct_M_istar(p, 2*len(interfaces), len(interfaces))
print(np.sum(M, axis=1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
# get stationary distrib
#------------------------
def get_summation_distr(M):
    # This is actually an eigenvector of M, with just ones in it.
    a = M-np.identity(len(M))
    # this would just be a constanct vector
    vals, vecs = np.linalg.eig(a)
    print(vals)
    order = np.argsort(abs(vals))
    vals = vals[order]
    print(vals)
    vec = vecs[:,order[0]]
    print(vec)

def get_stationary_distr(M):
    """Calculate stationary distr of M
    First substract identity matrix, such that
    the stationary vector is the LEFT eigenvecor of M
    corresponding with eigenvalue 0"""
    # for i in range(len(M)):
    #     if np.sum(M[:,i])==0:
    #         M = np.delete(np.delete(M, i, axis=0), i, axis=1)
    a = M-np.identity(len(M))

    vals, vecs = np.linalg.eig(a.T)
    #print(vals)
    order = np.argsort(abs(vals))
    vals = vals[order]
    #print(vals)
    vec = vecs[:,order[0]]
    #print(vec)

    # make vector positive
    if max(vec) < 0:
        vec *= -1
    # remove imaginary part of vector
    if np.sum(abs(vec-vec.real)) < 1e-8:
        vec = vec.real
    # all elements should be larger than zero
    assert vec.all()>=0
    #assert abs(np.sum(vec**2)-1) < 1e-8 # normalization is automatic
    # renormalize to sum=1
    vec /= np.sum(vec)
    return vec

summ_d = get_summation_distr(M)
stat_d = get_stationary_distr(M)
print("summation distr", summ_d)
print("stationary distr", stat_d)

[-1.00000000e+00+0.j        -4.44089210e-16+0.j
 -1.97847851e+00+0.j        -1.88769425e+00+0.j
 -1.45557939e-01+0.j        -1.59843294e+00+0.j
 -1.55399924e+00+0.j        -3.72142810e-01+0.j
 -1.00007190e+00+0.3178658j -1.00007190e+00-0.3178658j
 -1.35225211e+00+0.j        -1.34660170e+00+0.j
 -1.27890837e+00+0.j        -1.24937129e+00+0.j
 -1.00000000e+00+0.j        -4.64759930e-01+0.j
 -6.41902690e-01+0.j        -6.58147086e-01+0.j
 -7.20930002e-01+0.j        -7.50677337e-01+0.j       ]
[-4.44089210e-16+0.j        -1.45557939e-01+0.j
 -3.72142810e-01+0.j        -4.64759930e-01+0.j
 -6.41902690e-01+0.j        -6.58147086e-01+0.j
 -7.20930002e-01+0.j        -7.50677337e-01+0.j
 -1.00000000e+00+0.j        -1.00000000e+00+0.j
 -1.00007190e+00+0.3178658j -1.00007190e+00-0.3178658j
 -1.24937129e+00+0.j        -1.27890837e+00+0.j
 -1.34660170e+00+0.j        -1.35225211e+00+0.j
 -1.55399924e+00+0.j        -1.59843294e+00+0.j
 -1.88769425e+00+0.j        -1.97847851e+00+0.j       ]
[-0.223606

In [28]:
# Create state labels for better readability
N = len(interfaces)
labels = generate_state_labels(N)

# Get different color/alpha combinations for each run
color_pairs = [('darkgreen', 'darkblue'), 
                ('purple', 'maroon'), ('orange', 'navy')]  # Add more pairs if needed
alpha_values = [0.5, 0.6, 0.7, 0.8]  # Different alpha values for different runs

# Get the current axis if it exists, otherwise create new figure
if plt.get_fignums():
    # Get the current figure
    fig = plt.gcf()
    ax1, ax2 = fig.axes
    
    # Use the next available color pair and alpha value
    used_runs = len([ax for ax in fig.axes if ax.patches])
    bar_color1, bar_color2 = color_pairs[used_runs % len(color_pairs)]
    alpha_val = alpha_values[used_runs % len(alpha_values)]
else:
    # Create a figure with two subplots for the first run
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), gridspec_kw={'height_ratios': [1, 1]})
    bar_color1, bar_color2 = color_pairs[0]
    alpha_val = alpha_values[0]

# Plot the stationary distribution as a bar chart with transparency
ax1.bar(range(len(stat_d)), stat_d, color=bar_color1, alpha=alpha_val, 
        label=f"{indir.split('/')[-2]}")
ax1.set_xticks(range(len(stat_d)))
ax1.set_xticklabels(labels, rotation=45, ha='right')
ax1.set_xlabel("State")
ax1.set_ylabel("Stationary Probability")
ax1.set_title("Stationary Distribution")
ax1.grid(axis='y', linestyle='--', alpha=0.7)
ax1.legend()

# Calculate the free energy: -ln(prob)
# Handle zero probabilities by setting them to NaN to avoid -inf
free_energy = -np.log(np.where(stat_d > 0, stat_d, np.nan))

# Plot the free energy with transparency
ax2.bar(range(len(stat_d)), free_energy, color=bar_color2, alpha=alpha_val, 
        label=f"{indir.split('/')[-2]}")
ax2.set_xticks(range(len(stat_d)))
ax2.set_xticklabels(labels, rotation=45, ha='right')
ax2.set_xlabel("State")
ax2.set_ylabel("Free Energy (-ln(P))")
ax2.set_title("Free Energy Landscape")
ax2.grid(axis='y', linestyle='--', alpha=0.7)
ax2.legend()

# Improve layout
plt.tight_layout()
plt.show()


In [13]:
print(stat_d[-1]/(stat_d[-2]+stat_d[-1]))
print(stat_d[-3]/np.sum(stat_d[-3:]))
print((np.sum(stat_d[2:len(interfaces)-1])/np.sum(stat_d[2:len(interfaces)+1]))*stat_d[-3]/np.sum(stat_d[-3:]))
print((np.sum(stat_d[2:len(interfaces)-2])/np.sum(stat_d[2:len(interfaces)+1]))*stat_d[-4]/np.sum(stat_d[-4:]))
print(stat_d[-3]/(stat_d[-3]+stat_d[-2]*(np.sum(stat_d[2:len(interfaces)-1])/np.sum(stat_d[2:len(interfaces)]))+stat_d[-1]*(np.sum(stat_d[2:len(interfaces)-1])/np.sum(stat_d[2:len(interfaces)+1]))))
print(stat_d[-3]/np.sum(stat_d[-3:]))
print(stat_d[4]/(stat_d[3]+stat_d[4]+stat_d[1]))

for i in range(3,len(pathensembles)+1):
    print(f"relative stat_d, turn fw {i-2}: {stat_d[i]/(stat_d[1]+np.sum(stat_d[2:i+1]))}")
for i in range(len(pathensembles)+1,2*len(pathensembles)-1):
    print(f"relative stat_d, turn bw {i-len(pathensembles)}: {stat_d[i]/np.sum(stat_d[i:])}")

0.5581818522322163
0.3952675653129849
0.3925948892990223
0.3310840920832566
0.3968904552024979
0.3952675653129849
0.18840312271464443
relative stat_d, turn fw 1: 0.05156509964361252
relative stat_d, turn fw 2: 0.040887681087811795
relative stat_d, turn fw 3: 0.018348109171564455
relative stat_d, turn fw 4: 0.06438938086945617
relative stat_d, turn fw 5: 0.011969154609128556
relative stat_d, turn fw 6: 0.01283455981317835
relative stat_d, turn fw 7: 0.005998984297083711
relative stat_d, turn fw 8: 0.0
relative stat_d, turn bw 1: 0.18175229339526647
relative stat_d, turn bw 2: 0.1978602551246124
relative stat_d, turn bw 3: 0.25923136523503415
relative stat_d, turn bw 4: 0.08956348826467248
relative stat_d, turn bw 5: 0.45123197521330494
relative stat_d, turn bw 6: 0.33823479354849456
relative stat_d, turn bw 7: 0.3952675653129849
relative stat_d, turn bw 8: 0.4418181477677837


In [13]:
def analyze_nonequilibrium_flux(M, interfaces, n_int=None, group_first=3):
    """
    Analyze non-equilibrium steady-state fluxes between interfaces.
    
    Parameters
    ----------
    M : numpy.ndarray
        Non-reversible transition matrix
    interfaces : list
        List of interface positions
    n_int : int, optional
        Number of interfaces to consider
    group_first : int, optional
        Number of initial states to group together in visualization (default: 3)
        
    Returns
    -------
    dict
        Dictionary with non-equilibrium analysis results
    """
    import numpy as np
    import matplotlib.pyplot as plt
    import networkx as nx
    
    if n_int is None:
        n_int = len(interfaces)
    
    # Find the stationary distribution using power iteration (robust for non-reversible matrices)
    n_states = M.shape[0]
    pi = np.ones(n_states) / n_states
    
    for _ in range(1000):
        pi_new = pi @ M
        change = np.linalg.norm(pi - pi_new/pi_new.sum())
        pi = pi_new / pi_new.sum()
        
        if change < 1e-10:
            break
    
    # Calculate the flux matrix
    flux = np.zeros_like(M)
    for i in range(n_states):
        for j in range(n_states):
            flux[i, j] = pi[i] * M[i, j]
    
    # Calculate the net flux matrix (flux - backwards flux)
    net_flux = flux - flux.T
    
    # Create a network visualization of the non-equilibrium fluxes
    G = nx.DiGraph()
    
    # Add nodes (with special handling for grouped nodes)
    for i in range(n_states):
        # Determine if this is an A-side or B-side state
        if i < n_int:
            side = 'A'
            interface = i
        else:
            side = 'B'
            interface = i - n_int
        
        # Add node attributes
        G.add_node(i, side=side, interface=interface, probability=pi[i])
    
    # Add edges with flux values
    for i in range(n_states):
        for j in range(n_states):
            if M[i, j] > 0:
                G.add_edge(i, j, flux=flux[i, j], net_flux=net_flux[i, j], 
                          transition_prob=M[i, j])
    
    # Calculate net fluxes between interface layers
    layer_fluxes = np.zeros((n_int, n_int))
    
    for i in range(n_states):
        for j in range(n_states):
            if flux[i, j] > 0:
                # Convert to interface indices
                i_interface = i % n_int
                j_interface = j % n_int
                layer_fluxes[i_interface, j_interface] += flux[i, j]
    
    # Calculate cyclic fluxes (a measure of non-reversibility)
    # Cycle detection in the graph
    cycles = list(nx.simple_cycles(G))
    cycle_fluxes = []
    
    for cycle in cycles:
        if len(cycle) > 1:  # Skip self-loops
            # Calculate the flux around this cycle
            cycle_flux = float('inf')
            for i in range(len(cycle)):
                j = (i + 1) % len(cycle)
                edge_flux = G.edges[cycle[i], cycle[j]]['flux']
                cycle_flux = min(cycle_flux, edge_flux)
                
            cycle_fluxes.append((cycle, cycle_flux))
    
    # Sort cycles by flux magnitude
    cycle_fluxes.sort(key=lambda x: x[1], reverse=True)
    
    # Calculate local crossing probabilities
    ploc_forward = np.zeros(n_int-1)
    ploc_backward = np.zeros(n_int-1)
    
    for i in range(n_int-1):
        # Forward probability (A->B)
        if pi[i] > 0:
            forward_flux = sum(flux[i, j] for j in range(n_int, 2*n_int))
            ploc_forward[i] = forward_flux / pi[i]
        
        # Backward probability (B->A)
        i_b = i + n_int
        if pi[i_b] > 0:
            backward_flux = sum(flux[i_b, j] for j in range(n_int))
            ploc_backward[i] = backward_flux / pi[i_b]
    
    # Visualization
    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    
    # Plot stationary distribution
    state_labels = [f"{i % n_int}({'A' if i < n_int else 'B'})" for i in range(n_states)]
    
    axes[0, 0].bar(range(n_states), pi, color=['blue' if i < n_int else 'red' for i in range(n_states)])
    axes[0, 0].set_xticks(range(n_states))
    axes[0, 0].set_xticklabels(state_labels, rotation=90)
    axes[0, 0].set_title('Non-Equilibrium Steady State Distribution')
    
    # Plot net flux matrix
    im = axes[0, 1].imshow(net_flux, cmap='RdBu', vmin=-np.max(np.abs(net_flux)), 
                          vmax=np.max(np.abs(net_flux)))
    axes[0, 1].set_title('Net Flux (Non-Equilibrium Effects)')
    plt.colorbar(im, ax=axes[0, 1])
    
    # Plot local crossing probabilities
    x = range(n_int-1)
    axes[1, 0].plot(x, ploc_forward, 'o-', label='Forward (A→B)', color='green')
    axes[1, 0].plot(x, ploc_backward, 's--', label='Backward (B→A)', color='orange')
    axes[1, 0].set_xlabel('Interface')
    axes[1, 0].set_xticks(x)
    axes[1, 0].set_ylabel('Crossing Probability')
    axes[1, 0].set_title('Local Interface Crossing Probabilities')
    axes[1, 0].legend()
    axes[1, 0].grid(alpha=0.3)
    
    # Network visualization of the strongest cycles (if any)
    if cycle_fluxes:
        # Create a simplified graph for visualization
        G_vis = nx.DiGraph()
        
        # Create node groups
        node_mapping = {}
        for i in range(n_states):
            if i < group_first and i < n_int:
                # Group the first few A states
                node_mapping[i] = f"0-{group_first-1}(A)"
            else:
                # Keep other nodes as is
                side = 'A' if i < n_int else 'B'
                interface = i % n_int
                node_mapping[i] = f"{interface}({side})"
        
        # Add nodes to the visualization graph
        for node_id, node_label in node_mapping.items():
            if node_label not in G_vis:
                side = G.nodes[node_id]['side']
                # Aggregate probabilities for grouped nodes
                if (node_label == f"0-{group_first-1}(A)" or 
                    node_label == f"0-{group_first-1}(B)"):
                    
                    start_idx = 0 if side == 'A' else n_int
                    end_idx = group_first if side == 'A' else (n_int + group_first)
                    prob = sum(pi[i] for i in range(start_idx, end_idx))
                else:
                    prob = G.nodes[node_id]['probability']
                
                G_vis.add_node(node_label, probability=prob, side=side)
        
        # Add edges with aggregated fluxes
        edge_fluxes = {}
        for i, j in G.edges:
            source = node_mapping[i]
            target = node_mapping[j]
            if (source, target) not in edge_fluxes:
                edge_fluxes[(source, target)] = 0
            edge_fluxes[(source, target)] += G.edges[i, j]['flux']
        
        for (source, target), flux_value in edge_fluxes.items():
            G_vis.add_edge(source, target, flux=flux_value, is_self_loop=(source == target))
        
        # Find top non-recursive transitions
        non_recursive_edges = [(s, t, data['flux']) for s, t, data in G_vis.edges(data=True) 
                                if not data['is_self_loop']]
        top_edges = sorted(non_recursive_edges, key=lambda x: x[2], reverse=True)[:3]
        top_edges_set = {(s, t) for s, t, _ in top_edges}
        
        # Draw the network graph with the strongest cycles highlighted
        pos = nx.spring_layout(G_vis, seed=42)
        
        # Node colors by side
        node_colors = ['blue' if G_vis.nodes[n]['side'] == 'A' else 'red' for n in G_vis.nodes]
        
        # Size by probability
        node_sizes = [3000 * G_vis.nodes[n]['probability'] + 100 for n in G_vis.nodes]
        
        # Draw nodes
        nx.draw_networkx_nodes(G_vis, pos, ax=axes[1, 1], node_color=node_colors, 
                             node_size=node_sizes, alpha=0.7)
        
        # Draw node labels
        nx.draw_networkx_labels(G_vis, pos, ax=axes[1, 1])
        
        # Draw regular edges
        regular_edges = [(u, v) for u, v in G_vis.edges() if (u, v) not in top_edges_set and u != v]
        regular_widths = [G_vis.edges[e]['flux'] * 20 + 0.5 for e in regular_edges]
        nx.draw_networkx_edges(G_vis, pos, ax=axes[1, 1], edgelist=regular_edges, 
                             width=regular_widths, alpha=0.3, edge_color='gray')
        
        # Draw self-loops
        self_loops = [(u, v) for u, v in G_vis.edges() if u == v]
        self_loop_widths = [G_vis.edges[e]['flux'] * 20 + 0.5 for e in self_loops]
        nx.draw_networkx_edges(G_vis, pos, ax=axes[1, 1], edgelist=self_loops, 
                             width=self_loop_widths, alpha=0.2, edge_color='lightgray',
                             connectionstyle="arc3,rad=0.3")
        
        # Highlight top non-recursive transitions
        if top_edges:
            top_widths = [G_vis.edges[(s, t)]['flux'] * 20 + 1.0 for s, t, _ in top_edges]
            nx.draw_networkx_edges(G_vis, pos, ax=axes[1, 1], edgelist=[(s, t) for s, t, _ in top_edges], 
                                 width=top_widths, alpha=0.9, edge_color='green', 
                                 arrows=True, arrowsize=15)
            
            # Add edge labels for top transitions
            edge_labels = {(s, t): f"{flux:.2e}" for s, t, flux in top_edges}
            nx.draw_networkx_edge_labels(G_vis, pos, edge_labels=edge_labels, ax=axes[1, 1], 
                                       font_size=8, label_pos=0.3)
            
            axes[1, 1].set_title('Network with Top 3 Non-Recursive Transitions Highlighted')
        else:
            axes[1, 1].set_title('Network (No Significant Non-Recursive Transitions)')
    else:
        axes[1, 1].set_visible(False)
    
    plt.tight_layout()
    
    return {
        'ploc_forward': ploc_forward,
        'ploc_backward': ploc_backward,
        'stationary_distribution': pi,
        'flux': flux,
        'net_flux': net_flux,
        'cycles': cycle_fluxes
    }


In [15]:
analyze_nonequilibrium_flux(M, interfaces, len(interfaces))

{'ploc_forward': array([0.        , 0.        , 0.82331662, 1.        , 1.        ,
        1.        ]),
 'ploc_backward': array([0., 1., 0., 1., 1., 1.]),
 'stationary_distribution': array([0.26325134, 0.05006568, 0.26325134, 0.0020677 , 0.07524077,
        0.02603776, 0.        , 0.        , 0.00396633, 0.        ,
        0.03356695, 0.11155875, 0.00431987, 0.16667353]),
 'flux': array([[0.00000000e+00, 0.00000000e+00, 2.63251338e-01, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00],
        [5.00656765e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00],
        [4.65121353e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000

In [12]:
# Create a time-reversible version of a transition matrix M with disconnected sets

import numpy as np
import matplotlib.pyplot as plt

# Compute the stationary distributions of the original matrix M
eigenvalues, eigenvectors = np.linalg.eig(M.T)
idx = np.where(np.isclose(eigenvalues, 1.0))[0]
stationary_vecs = eigenvectors[:, idx].real

# Identify disconnected components
disconnected_sets = []
n = M.shape[0]
visited = np.zeros(n, dtype=bool)

for i in range(n):
    if not visited[i]:
        # Find states reachable from i
        component = set()
        to_visit = [i]
        while to_visit:
            state = to_visit.pop()
            if not visited[state]:
                visited[state] = True
                component.add(state)
                for j in range(n):
                    if M[state, j] > 0 and not visited[j]:
                        to_visit.append(j)
        
        disconnected_sets.append(list(component))

print(f"Identified {len(disconnected_sets)} disconnected components:")
for i, component in enumerate(disconnected_sets):
    print(f"Component {i+1}: {component}")

# Identify states that can't be reached by any other state
unreachable_states = set()
for i in range(n):
    has_incoming = False
    for j in range(n):
        if i != j and M[j, i] > 0:
            has_incoming = True
            break
    if not has_incoming:
        unreachable_states.add(i)

if unreachable_states:
    print(f"States with no incoming transitions: {unreachable_states}")

# Compute stationary distribution for each component
pi_full = np.zeros(n)
for component in disconnected_sets:
    # Filter out unreachable states from the component
    valid_component = [s for s in component if s not in unreachable_states]
    
    if not valid_component:  # Skip if all states in component are unreachable
        continue
        
    # Extract submatrix for this component
    subset_idx = np.array(valid_component)
    submatrix = M[np.ix_(subset_idx, subset_idx)]
    
    # Find stationary distribution for this submatrix
    sub_eigen_vals, sub_eigen_vecs = np.linalg.eig(submatrix.T)
    
    # Check if there's a valid eigenvalue close to 1.0
    sub_idx_candidates = np.where(np.isclose(sub_eigen_vals, 1.0, atol=0.01))[0]
    
    if len(sub_idx_candidates) == 0:
        print(f"Warning: Component {valid_component} has no eigenvalue close to 1.0, skipping")
        continue
    
    sub_idx = sub_idx_candidates[0]  # Take first eigenvalue ≈ 1
    
    stationary_sub = sub_eigen_vecs[:, sub_idx].real
    
    # Check if the stationary distribution sums to a non-zero value
    if np.abs(stationary_sub.sum()) < 1e-10:
        print(f"Warning: Component {valid_component} has zero stationary distribution, skipping")
        continue
        
    stationary_sub = stationary_sub / stationary_sub.sum()  # Normalize
    
    # Place into full stationary vector
    pi_full[subset_idx] = stationary_sub

# Create a reversible transition matrix
M_reversible = np.zeros_like(M)

# For each component, apply reversibility correction
for component in disconnected_sets:
    # Filter out unreachable states
    valid_states = [s for s in component if s not in unreachable_states]
    
    for i in valid_states:
        for j in valid_states:
            # Skip if either probability is 0 (maintain sparsity)
            if M[i,j] > 0 or M[j,i] > 0:
                # Symmetric rate that preserves detailed balance
                if pi_full[i] > 0 and pi_full[j] > 0:
                    M_reversible[i,j] = (M[i,j] + (pi_full[j]/pi_full[i]) * M[j,i]) / 2

# Fix diagonal to ensure rows sum to 1
for i in range(n):
    if i not in unreachable_states:  # Only adjust diagonal for reachable states
        M_reversible[i,i] = 1.0 - np.sum(M_reversible[i,:]) + M_reversible[i,i]

# Verify reversibility
valid_states = np.array([i not in unreachable_states for i in range(n)])
valid_indices = np.where(valid_states)[0]
pi_valid = pi_full[valid_indices]
M_valid = M_reversible[np.ix_(valid_indices, valid_indices)]

# Check detailed balance condition: pi_i * P_ij = pi_j * P_ji
pi_matrix = pi_valid[:, np.newaxis] * M_valid
reversibility_check = np.abs(pi_matrix - pi_matrix.T)
max_violation = np.max(reversibility_check)
print(f"Maximum detailed balance violation: {max_violation:.2e}")

# Create full version of M_valid for proper comparison with M
M_reversible_display = np.full_like(M, np.nan)
M_reversible_display[np.ix_(valid_indices, valid_indices)] = M_valid

# Plot the original and reversible matrices
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

im1 = ax1.imshow(M, cmap='viridis')
ax1.set_title("Original Transition Matrix")
plt.colorbar(im1, ax=ax1)

im2 = ax2.imshow(M_reversible_display, cmap='viridis')
ax2.set_title("Reversible Transition Matrix")
plt.colorbar(im2, ax=ax2)

plt.tight_layout()
plt.show()

print("Original matrix M:")
print(M)
print("\nReversible matrix:")
print(M_reversible_display)
print("\nStationary distribution:")
print(pi_full)

Identified 4 disconnected components:
Component 1: [0, 1, 2, 3, 4, 5, 8, 10, 11, 12, 13]
Component 2: [6]
Component 3: [7]
Component 4: [9]
States with no incoming transitions: {9, 6, 7}
Maximum detailed balance violation: 2.78e-17
Original matrix M:
[[0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.17668338 0.         0.         0.         0.         0.
  0.         0.         0.01506671 0.         0.06181814 0.22180695
  0.01095154 0.51367328]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.14455198 0.39738412
  0.01996033 0.43810357]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.22586624 0.45083092
  0.01321205 0.31009079]


In [13]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from scipy import sparse
from scipy.sparse.csgraph import connected_components, shortest_path
from tistools import analyze_network_connectivity, find_network_bottlenecks, calculate_effective_transitions

# Define the analysis functions
# [Copy the functions above here]

# Analyze network connectivity in your MSM transition matrix
if 'M' in locals():
    # Assuming M is your transition matrix
    print("Analyzing network connectivity structure...")
    
    # Determine if we are using the iSTAR model with 2N states
    n_interfaces = M.shape[0] // 2 if M.shape[0] % 2 == 0 else None
    
    if n_interfaces:
        print(f"Detected {n_interfaces} interfaces with {M.shape[0]} states.")
        # Check overall network connectivity
        connectivity = analyze_network_connectivity(M)
        print(f"Network has {connectivity['n_strong_components']} strongly connected components")
        print(f"Direct path from source to sink exists: {connectivity['direct_path_exists']}")
        
        if connectivity['critical_nodes']:
            print(f"Critical bridge states: {connectivity['critical_nodes']}")
            
        # Analyze bottlenecks
        bottlenecks = find_network_bottlenecks(M)
        if bottlenecks:
            print(f"Minimum cut value: {bottlenecks['cut_value']:.4f}")
            print(f"Cut edges: {bottlenecks['cut_edges']}")
            
        # Calculate effective transition probabilities
        effective_transitions = calculate_effective_transitions(M, max_steps=50)
        print(f"Effective transition probability: {effective_transitions['effective_probability']:.6f}")
        
        plt.figure(figsize=(10, 6))
        plt.plot(effective_transitions['cumulative_probabilities'], 'r.-')
        plt.xlabel('Number of Steps')
        plt.ylabel('Cumulative Probability')
        plt.title('Probability of Reaching Sink State from Source')
        plt.grid(True, alpha=0.3)
        plt.show()
    else:
        print("Could not determine network structure. Please provide the number of interfaces.")
else:
    print("Transition matrix 'M' not found. Please calculate it first.")

Analyzing network connectivity structure...
Detected 7 interfaces with 14 states.
Network has 4 strongly connected components
Direct path from source to sink exists: True
Critical bridge states: {2}
Minimum cut value: 0.8082
Cut edges: [(2, 10), (2, 11), (2, 12), (2, 13)]
Effective transition probability: 0.513673


In [28]:
pcca = pcca_analysis(M_valid, 5)
committor = dpt.markov.tools.analysis.committor(M, [0, 1], [M.shape[0]-1,])
print("Committor probabilities:")
print(committor)

PCCA+ Membership Matrix:
[[6.41811142e-01 3.55584236e-01 1.75361337e-06 2.60286812e-03
  9.29200524e-17]
 [0.00000000e+00 0.00000000e+00 1.16883025e-01 2.81923497e-01
  6.01193478e-01]
 [5.87854300e-06 9.54445419e-04 1.38361534e-01 3.24535808e-01
  5.36142334e-01]
 [9.92401241e-02 5.87027015e-03 3.33121785e-02 8.47467292e-02
  7.76830698e-01]
 [2.14144217e-01 9.30686102e-04 1.36970537e-02 2.84054354e-02
  7.42822607e-01]
 [3.78069925e-01 1.21107061e-03 5.19797329e-03 5.24080749e-03
  6.10280223e-01]
 [5.22457553e-01 2.22921640e-02 0.00000000e+00 2.77038153e-03
  4.52479902e-01]
 [5.89227174e-01 3.50762917e-01 2.91247258e-02 0.00000000e+00
  3.08851837e-02]
 [2.57903164e-01 2.36617222e-01 2.22833698e-01 1.39500745e-02
  2.68695841e-01]
 [8.82856902e-02 1.49265076e-01 3.55918627e-01 4.02686101e-02
  3.66261997e-01]
 [1.64162499e-02 6.72136283e-02 4.63099026e-01 8.47090330e-02
  3.68562063e-01]
 [3.65907802e-03 9.26356442e-04 5.34619633e-01 1.36015268e-01
  3.24779664e-01]
 [2.11354912e-0

In [29]:
print("Using msmtools will also work for hitting probs.")
# Let's try with msmtools, this should definitely work as well.
# I already know I can't solve the MFPT question with this, but 
# this might come in handy whenever we DO include multidimensionality
# from msmtools.analysis import (is_transition_matrix, is_connected, mfpt, 
#                                stationary_distribution, is_reversible)
from deeptime.markov.tools.estimation import is_connected, largest_connected_set, largest_connected_submatrix
from deeptime.markov.tools.analysis import stationary_distribution, is_transition_matrix, is_reversible

print("Using transition matrix with disconnected states: ")
print("is_tmat: ", is_transition_matrix(M_valid))
print("is_connected: ", is_connected(M_valid))
print("largest conn set: ", largest_connected_set(M_valid))
print("stationary_distribution: ", stationary_distribution(largest_connected_submatrix(M_valid)))
print("is_reversible: ", is_reversible(M_valid))

Using msmtools will also work for hitting probs.
Using transition matrix with disconnected states: 
is_tmat:  True
is_connected:  True
largest conn set:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
stationary_distribution:  [0.3083576  0.07011318 0.3083576  0.04931468 0.03051761 0.01877598
 0.00862859 0.03478972 0.048818   0.0434959  0.03170973 0.01853669
 0.02858472]
is_reversible:  True


In [18]:
# define states A and B
A = [1]
B = [-2]
# Get the committtor probabilities
from msmtools.analysis import committor
from msmtools.flux import tpt
test = tpt(M_valid[1:-1,1:-1], A, B)
print("Same value?", (pmp0plus * plocs[0][-1][1] * test.committor)[0])
print("Real value:", 0.00020540578383777418)
print("So this works as expected")

ModuleNotFoundError: No module named 'msmtools'

In [30]:
import numpy as np
import networkx as nx
from matplotlib.colors import LinearSegmentedColormap

# Compute flux matrix and identify dominant pathways
import matplotlib.pyplot as plt

# Define initial and final states
initial_states = [0,1]  # First state (typically state A)
final_states = [len(M_valid)-1,]  # Last state (typically state B)

# Create a ReactiveFlux object
flux = dpt.markov.reactive_flux(M_valid, source_states=initial_states, target_states=final_states)

# Get the flux matrix
flux_matrix = flux.net_flux
print("Flux M_validatrix:")
print(flux_matrix)

# Get the total flux
total_flux = flux.gross_flux
print("Total Flux:") 
print(np.sum(total_flux))

# Identify dominant pathways
paths, path_fluxes = flux.pathways(fraction=1)  # Extract paths accounting for 95% of total flux
print("\nDominant Pathways:")
for i, (path, path_flux) in enumerate(zip(paths, path_fluxes)):
    # Format path with state names
    path_str = " → ".join([f"{state}" for state in path])
    percentage = path_flux / flux.total_flux * 100
    print(f"Path {i+1}: {path_str}")
    print(f"  Flux: {path_flux:.6e} ({percentage:.2f}% of total flux)")

# Create a more appealing visualization of the flux network
plt.figure(figsize=(12, 8))

# Create a directed graph
G = nx.DiGraph()

# Add nodes with positions arranged in a circle
n_nodes = M_valid.shape[0]

# Use string labels for nodes based on interfaces for better readability
if 'labels1' in globals() and 'labels2' in globals():
    # If we have labels defined in earlier cells, use them
    node_labels = []
    for i in range(n_nodes):
        if i < len(labels1):
            node_labels.append(labels1[i])
        elif i < len(labels1) + len(labels2):
            node_labels.append(labels2[i - len(labels1)])
        else:
            node_labels.append(f"State {i}")
else:
    # Default to numeric labels
    node_labels = [f"State {i}" for i in range(n_nodes)]

# Add nodes with attributes
for i in range(n_nodes):
    G.add_node(i, label=node_labels[i])

# Add edges with weights from the flux matrix
for i in range(n_nodes):
    for j in range(n_nodes):
        if flux_matrix[i, j] > 0:
            G.add_edge(i, j, weight=flux_matrix[i, j])

# Get positions in a circular layout
pos = nx.circular_layout(G)

# Create a custom colormap for the edges (blue to red)
cmap = LinearSegmentedColormap.from_list("flux_cmap", ["lightblue", "blue", "darkblue"])

# Draw the graph
edges = G.edges()
weights = [G[u][v]['weight'] for u, v in edges]
max_weight = max(weights) if weights else 1.0
norm_weights = [w / max_weight for w in weights]

# Draw nodes with different colors for source, target, and intermediate states
node_colors = []
for node in G.nodes():
    if node in initial_states:
        node_colors.append('lightgreen')  # Source states in green
    elif node in final_states:
        node_colors.append('red')  # Target states in red
    else:
        node_colors.append('lightgray')  # Intermediate states in gray

# Draw the network
nx.draw_networkx_nodes(G, pos, node_color=node_colors, node_size=800, alpha=0.8)
nx.draw_networkx_labels(G, pos, labels={i: node_labels[i] for i in range(n_nodes)}, font_size=10)
nx.draw_networkx_edges(G, pos, width=[30 * w for w in norm_weights], 
                       edge_color=norm_weights, edge_cmap=cmap, 
                       connectionstyle='arc3,rad=0.1', arrowsize=20, alpha=0.7)

# Add edge labels with flux values
edge_labels = {(u, v): f"{G[u][v]['weight']:.2e}" for u, v in G.edges()}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8)

plt.title("Reactive Flux Network")
plt.axis('off')
plt.tight_layout()
plt.show()

# Calculate committor probabilities
forward_committor = flux.forward_committor
backward_committor = flux.backward_committor

print("\nForward Committor Probabilities (probability to reach target before returning to source):")
for i in range(len(forward_committor)):
    print(f"State {i}: {forward_committor[i]:.4f}")

print("\nBackward Committor Probabilities (probability to have come from source rather than target):")
for i in range(len(backward_committor)):
    print(f"State {i}: {backward_committor[i]:.4f}")

Flux M_validatrix:
[[0.         0.         0.00700944 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.01429236]
 [0.         0.         0.         0.         0.         0.
  0.         0.00023537 0.00112691 0.00094386 0.00055584 0.00021722
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.00125965 0.00128123 0.00101789 0.00066446
  0.00302158]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.00031809 0.00035783
  0.00206521]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.00017902
  0.00194618]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.0018709 ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.00118475]
 [0.       

In [ ]:
# make_plot_trajs("paths002test", "./002", interfaces, 5)

In [ ]:
# if 'repptis' in fol:
#     plot_rv_repptis(pathensembles, interfaces, 3)
# else:
#     plot_rv_star(pathensembles, interfaces, 1)

In [ ]:
# plot_rv_comp(pathensembles, interfaces, 1, 1, (2,4))
# while True:
#     try:
#         plot_rv_comp(pathensembles, interfaces, 1, 1, (2,4))
#         break
#     except:
#         plt.close("all")
#         continue

# Analysis

In [ ]:
# Setting path ensemble properties
#==================================
# for i,fol in enumerate(folders):
#     print(i)
#     if i != 1:
#         print("Calculating path lengths.")
#         set_tau_distrib(pathensembles[i])
#     print("Done.")
#     #else:
#         #TODO problem with ...
#     if i > 1:
#         print("Calculating first hitting lengths to middle interface")
#         set_tau_first_hit_M_distrib(pathensembles[i])
#         print("Done.")
#     #else:
#         # TODO problem with ....

In [ ]:
# Analyze the [i*] simulation.
# Analysis output is saved to the data dictionary.
data = {}

data["running"] = {}

# analysis using all data: ["full"]
# data["full"] = get_transition_probs(pathensembles, interfaces)
# pprint(data)
# print("\n\n")
# data["full"] = get_transition_probzz2(pathensembles, interfaces)
w = compute_weight_matrices(pathensembles, interfaces, tr=True)
for i in range(len(pathensembles)):
    print(f"sum weights pe {i}: ",np.sum(w[i]))

data["full"], _ = get_transition_probs_weights(w)
# data["full"] = get_transition_probs(w)
data["full1"] = get_simple_probs(w)
# data["full"] = get_summed_probs(pathensembles, interfaces)
pprint(data)

weights:
accepted      77751
rejected      22249
omitted       0
total trajs   100000
total weights 100000
Sum weights ensemble 0:  0.0
weights:
accepted      58518
rejected      41482
omitted       0
total trajs   100000
total weights 100000
Sum weights ensemble 1:  99998.0
weights:
accepted      50666
rejected      49334
omitted       0
total trajs   100000
total weights 101416
Sum weights ensemble 2:  102339.0
weights:
accepted      47604
rejected      52396
omitted       0
total trajs   100000
total weights 124396
Sum weights ensemble 3:  124395.0
weights:
accepted      47614
rejected      52386
omitted       0
total trajs   100000
total weights 124047
Sum weights ensemble 4:  124046.0
weights:
accepted      51103
rejected      48897
omitted       0
total trajs   100000
total weights 101326
Sum weights ensemble 5:  101325.0
sum weights pe 0:  0.0
sum weights pe 1:  99998.0
sum weights pe 2:  102339.0
sum weights pe 3:  124395.0
sum weights pe 4:  124046.0
sum weights pe 5:  102143.

In [ ]:
# Make a figure of the global crossing probabilities
# fig, ax = plt.subplots()
# ax.set_yscale("log")
# ax.plot(Pcrossfull, "o", c = "r")

# cosdip meta
# ax.errorbar([i for i in range(7)], Pcrossfull, yerr=[0, 0.004830, Pcrossfull[2]*0.05068988646, Pcrossfull[3]*0.05189862680, Pcrossfull[4]*0.05071184896, Pcrossfull[5]*0.05083284286, Pcrossfull[6]*0.05067963543], fmt="-o", c = "b", ecolor="r", capsize=6)

# cosbump meta
# ax.errorbar([i for i in range(7)], Pcrossfull, yerr=[0, 0.002535, Pcrossfull[2]*0.04393065503, Pcrossfull[3]*0.04910273500, Pcrossfull[4]*0.05239942040, Pcrossfull[5]*0.05789033634, Pcrossfull[6]*0.0614468], fmt="-o", c = "b", ecolor="r", capsize=6)

# 2 cosdips
# ax.errorbar([i for i in range(5)], Pcrossfull, yerr=[0, 0.007239, Pcrossfull[2]*0.0414296, Pcrossfull[3]*0.0445266, Pcrossfull[4]*0.0483538], fmt="-o", c = "b", ecolor="r", capsize=6)

# 3 cosbumps
# ax.errorbar([i for i in range(7)], Pcrossfull, yerr=[0, 0.002295, Pcrossfull[2]*0.0328798, Pcrossfull[3]*0.031594, Pcrossfull[4]*0.031474, Pcrossfull[5]*0.03080392, Pcrossfull[6]*0.0308589], fmt="-o", c = "b", ecolor="r", capsize=6)

# 2 cosbumps
#ax.errorbar([i for i in range(5)], Pcrossfull, yerr=[0, 0.002768, Pcrossfull[2]*0.04440278, Pcrossfull[3]*0.043053, Pcrossfull[4]*0.0463156], fmt="-o", c = "b", ecolor="r", capsize=6)

# flat dt=0.00002 30k cycles
# ax.errorbar([i for i in range(5)], Pcrossfull, yerr=[0, 0.003294, Pcrossfull[2]*0.07640968, Pcrossfull[3]*0.07789262, Pcrossfull[4]*0.0812692], fmt="-o", c = "b", ecolor="r", capsize=6)

# flat 100k cycles
#ax.errorbar([i for i in range(5)], Pcrossfull, yerr=[0, 0.002741, Pcrossfull[2]*0.034092, Pcrossfull[3]*0.033621, Pcrossfull[4]*0.0398], fmt="-o", c = "b", ecolor="r", capsize=6)

# ax.set_xlabel("intf")
# ax.set_ylabel(r"$P_A(\lambda_i|\lambda_A)$")
# ax.set_xticks(np.arange(len(interfaces)))
# fig.tight_layout()
# fig.show()
# fig.savefig("Global_probs.pdf")

# print("This should be the same as the repptis_report.pdf value:", Pcrossfull[-1])
# print("which is the case!")
# print("Here, the load immediately disappeared. For a simulation where this is")
# print("not the case, the above code should be adapted a little bit.")

# Now work with MSM

In [ ]:
from tistools import construct_M
from tistools import global_pcross_msm
from tistools import mfpt_to_first_last_state

from tistools import create_labels_states

In [ ]:
def print_vector(g, states=None):
    if states is None:
        for i in range(len(g)):
            print("state", i, g[i])
    else:
        for i in range(len(g)):
            print("state", states[i], g[i][0])

In [ ]:
print(interfaces)
N = len(interfaces)
assert N >= 3
NS = 2*N
print("N", N)
print("NS", NS)

#labels2 = ["0+- LML","0+- LMR","0+- RML","1+- LML","1+- LMR",
#           "1+- RML", "1+- RMR", "2+- LML", "2+- LMR",
#           "2+- RML", "2+- RMR", "3+- LML", "3+- LMR",]
labels1, labels2 = create_labels_states(N)
print(labels1, labels2)

[-0.35, -0.25, -0.125, 0.0, 0.125, 0.25, 0.35]
N 7
NS 14
['0-     ', 'B      '] ['0+- LML', '0+- LMR', '0+- RML', '1+- LML', '1+- LMR', '1+- RML', '1+- RMR', '2+- LML', '2+- LMR', '2+- RML', '2+- RMR', '3+- LML', '3+- LMR', '3+- RML', '3+- RMR', '4+- LML', '4+- LMR', '4+- RML', '4+- RMR', '5+- LML', '5+- LMR']


In [ ]:
p_ini = data["full"]
print("p matrix: ", p_ini)
p_ini[-2][-1] = 1
print("sum rows of p:")
for i in range(p_ini.shape[0]):
    print(np.sum(p_ini[i][:i]), np.sum(p_ini[i][i:]))
M_valid = construct_M_istar(p_ini, NS, N)
M1 = construct_M_istar(data["full1"], NS, N)

# for r in range(M.shape[0]):
#     if np.sum(M[r]) != 0:
#         M[r] /= np.sum(M[r])
#Local crossing probabilities:
#pRMR = 0.34205627942625644.  #ppps
#pRML = 0.6579437205737436.   #ppms
#pLMR = 0.25316455696202533.  #pmps
#pLML = 0.7468354430379747.   #pmms

p matrix:  [[1.75548704e-01 1.46691326e-02 6.39395935e-06 6.08143573e-02
  2.22707863e-01 1.12157273e-02 5.15037822e-01]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 1.37216039e-01
  3.96635828e-01 1.63560748e-02 4.49792058e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.25749988e-01
  4.48488128e-01 1.27495437e-02 3.13012340e-01]
 [2.74886784e-01 1.52395039e-02 7.09873712e-01 0.00000000e+00
  7.13031858e-01 1.58610504e-02 2.71107091e-01]
 [3.12253402e-01 1.37575090e-02 4.49194466e-01 2.24794623e-01
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.61654351e-01 1.67585645e-02 3.74959518e-01 1.46627566e-01
  0.00000000e+00 0.00000000e+00 1.00000000e+00]
 [6.32073273e-01 1.35649184e-02 2.71195595e-01 7.40828782e-02
  0.00000000e+00 9.08333503e-03 0.00000000e+00]]
sum rows of p:
0.0 0.9999999999999998
1.0 1.0
0.0 1.0
1.0 1.0
1.0 0.0
1.0 1.0
1.0 0.0


In [ ]:
print("M")
print("shape", M_valid.shape)
print("sum prob in rows", np.sum(M_valid,axis=1))
print(M_valid)
print(M1)
# row 8, 10, 12, 14. # counting starts from 0   not okay!!!!

M
shape (12, 12)
sum prob in rows [1.         1.         0.99999361 1.         1.         1.
 1.         1.         1.         1.         1.         1.        ]
[[0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.1755487  0.         0.         0.         0.
  0.         0.01466913 0.06081436 0.22270786 0.01121573 0.51503782]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.13721604 0.39663583 0.01635607 0.44979206]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.22574999 0.44848813 0.01274954 0.31301234]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.71303186 0.01586105 0.27110709]
 [0.         0.         0.         0.         0.         0.
  0. 

# Look at this Markov model

In [ ]:
#import numpy.linalg
vals, vecs = np.linalg.eig(M_valid)
print(vals)
vals, vecs = np.linalg.eig(M_valid.T)
print(vals)

[ 0.00000000e+00+0.j          9.99998391e-01+0.j
 -4.06475700e-01+0.75408496j -4.06475700e-01-0.75408496j
 -6.94232447e-01+0.j          5.36024797e-01+0.j
  2.34678995e-01+0.j         -2.35629130e-01+0.j
 -2.75399289e-02+0.j         -5.82729603e-03+0.j
  5.47801777e-03+0.j          5.90239634e-16+0.j        ]
[ 9.99998391e-01+0.j         -4.06475700e-01+0.75408496j
 -4.06475700e-01-0.75408496j -6.94232447e-01+0.j
  5.36024797e-01+0.j          2.34678995e-01+0.j
 -2.35629130e-01+0.j         -2.75399289e-02+0.j
 -5.82729603e-03+0.j          5.47801777e-03+0.j
  4.49486924e-17+0.j          0.00000000e+00+0.j        ]


In [ ]:
print("what if chain propagates")
print("A[0,:]")
# check stationary behavior
A = M_valid
for n in range(10):
    A = np.dot(A,M_valid)
    #print(A)
    print(A[0,:])
    print(np.sum(A[0,:]))  # is 1 indeed

what if chain propagates
A[0,:]
[0.         0.1755487  0.         0.         0.         0.
 0.         0.01466913 0.06081436 0.22270786 0.01121573 0.51503782]
0.9999936060406505
[0.69058653 0.10610527 0.         0.00417865 0.1474151  0.05170806
 0.         0.         0.         0.         0.         0.        ]
0.9999936060406506
[0.10610527 0.         0.69058653 0.         0.         0.
 0.         0.         0.03385233 0.10464082 0.00276797 0.06204069]
0.9999936060406507
[0.06204069 0.16448942 0.10610527 0.00200188 0.07207283 0.02392855
 0.         0.01013031 0.04199758 0.15379905 0.00774543 0.35567818]
0.9999891904584801
[0.5201676  0.09190151 0.06204069 0.00288572 0.10180288 0.03570889
 0.         0.00155647 0.02299785 0.07381013 0.00252122 0.08459554]
0.9999885120256778
[0.17649706 0.04298084 0.5201676  0.00140817 0.05042603 0.0169618
 0.         0.00091008 0.02715093 0.08608049 0.00260735 0.07479777]
0.9999881153400327
[0.1177786  0.12777088 0.17649706 0.00164172 0.05891826 0.019

# Pcross with MSM

In [ ]:
# global crossing prob
z1, z2, y1, y2 = global_pcross_msm_star(M_valid, True)
print("Z")
print_vector(z1, labels1)
print_vector(z2, labels2)
print("Y")
print_vector(y1, labels1)
print_vector(y2, labels2)
print("global crossing prob", y1[0])


=== Eigenvalue Analysis ===
Mp eigenvalues: [ 0.     -0.6941  0.6941 -0.2346 -0.0058  0.0058  0.2346  0.      0.    ]
(I-Mp) eigenvalues: [1.     0.3059 1.6941 0.7654 0.9942 1.0058 1.2346 1.     1.    ]

=== Matrix Components ===
D (transitions from intermediate to boundary states):
[[0.     0.515 ]
 [0.     0.4498]
 [0.     0.313 ]
 [0.     0.2711]
 [0.     1.    ]
 [0.     0.    ]
 [0.     0.    ]
 [0.     0.    ]
 [0.     0.    ]]

E (transitions from boundary to intermediate states):
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

M11 (transitions between boundary states):
[0. 0.]

=== Solution Vectors ===
z1 (boundary states solution):
[[0]
 [1]]

z2 (intermediate states solution):
[[0.6349]
 [0.6746]
 [0.596 ]
 [0.5641]
 [1.    ]
 [0.    ]
 [0.4334]
 [0.4038]
 [0.3175]]

=== Result Vectors ===
y1 (boundary states result):
[[0.6349]
 [0.    ]]

y2 (intermediate states result):
[[0.6349]
 [0.6746]
 [0.596 ]
 [0.5641]
 [1.    ]
 [0.    ]
 [0.4334]
 [0.4038]
 [0.3175]]

In [ ]:
# P_loc with MSM
plocMSM = np.ones(len(interfaces))
# p2 = [1.0, 0.056804159591634415, 0.032312997136678026, 0.018071661236763906, 0.009174080897093834, 0.004218791762213937, 0.0019851528367788125, 0.0015222409020198072, 0.001318390278132916, 0.0011178599945945473, 0.0009802371708142466]
# p2 = [1.0, 0.8272598636455519, 0.8118884810440299, 0.7938415404869816, 0.5663700466714486, 0.5545303803303038]
# p2 = [1.0, 0.055139270922254895, 0.03126608951116539, 0.017392262443045026, 0.008894249404190929, 0.0040038338896561795, 0.0010513581251145503, 0.0010513581251145503, 0.0010513581251145503, 0.0010513581131851855, 0.0010513580976654149]
# p3 = [1.0, 0.062089, 0.035751653, 0.02010748, 0.010213876, 0.004782699, 0.001383816, 0.000568035, 0.000547059, 0.000516629, 0.000493516]
# p3 = [1.0, 0.810296, 0.796242226, 0.78048937, 0.636988594, 0.625611341]
# p3 = [1.0, 0.059440, 0.575552, 0.565633, 0.517311, 0.461832, 0.259615, 0.368699, 0.992271, 0.999820, 0.987496]
# p3 = [np.prod(p3[:i+1]) for i in range(len(p3))]

for lint in range(2, len(interfaces)+1):
    wi = compute_weight_matrices(pathensembles[:lint], interfaces[:lint], len(interfaces), True)
    pi, _ = get_transition_probs_weights(wi)
    # pi = get_transition_probs(wi)
    # pi = get_simple_probs(wi)
    Mi = construct_M_istar(pi, max(4, 2*len(interfaces[:lint])), len(interfaces[:lint]))
    z1, z2, y1, y2 = global_pcross_msm_star(Mi)
    plocMSM[lint-1] = y1[0][0]
    print(f"ploc till intf {lint-1}: ", y1[0][0])

# Make a figure of the global crossing probabilities
plt.rcParams['text.usetex'] = True
fig, ax = plt.subplots()
ax.set_yscale("log")
ax.plot(plocMSM, "o", c = "r")
ax.errorbar([i for i in range(len(plocMSM))], plocMSM, fmt="-o", c = "b", ecolor="r", capsize=6, label="StapleTIS")
# ax.errorbar([i for i in range(len(plocMSM))], p2, fmt="-o", c = "orange", ecolor="r", capsize=6., label="REPPTIS")
# ax.errorbar([i for i in range(len(plocMSM))], p3, fmt="-o", c = "r", ecolor="r", capsize=6., label="RETIS")
ax.set_xlabel(r"Interface index")
ax.set_ylabel(r"$P_A(\lambda_i|\lambda_A)$")
ax.set_xticks(np.arange(len(interfaces)))
fig.tight_layout()
fig.legend()
fig.show()


weights:
accepted      39957
rejected      60044
omitted       0
total trajs   100001
total weights 100001
sum weights ensemble 0= 0.0
weights:
accepted      38757
rejected      61244
omitted       0
total trajs   100001
total weights 100001
sum weights ensemble 1= 99998.0
0.0 [0. 0.] 1 0
q:  [[1.         0.08981925]
 [0.         0.        ]]
p:  [[0.91018075 0.08981925]
 [0.         0.        ]]
Local crossing probabilities computed
ploc till intf 1:  0.08981924986240757
weights:
accepted      39957
rejected      60044
omitted       0
total trajs   100001
total weights 100001
sum weights ensemble 0= 0.0
weights:
accepted      38757
rejected      61244
omitted       0
total trajs   100001
total weights 100001
sum weights ensemble 1= 99998.0
weights:
accepted      51081
rejected      48920
omitted       0
total trajs   100001
total weights 122225
sum weights ensemble 2= 171384.0
0 0 2 0.5403749317478614 16483.0
1 0 2 0.5268347225045741 98380.0
1 1 0 1.0 46550.0
1 1 2 1.0 73004.0
1 2 0 0

In [ ]:
print(plocMSM)
for pp in plocMSM:
    print(pp)
print("\n\n")
pcrosslocMSM = np.empty(len(plocMSM))

for i in range (len(pcrosslocMSM)):
    pcrosslocMSM[i] = plocMSM[i]/np.prod(pcrosslocMSM[:i])
    print(pcrosslocMSM[i])
    

[1.         0.08981925 0.04959346 0.03410001 0.02594881 0.02101857
 0.01758671 0.01516782 0.01335544 0.01189572 0.01073326 0.00976667
 0.00895838 0.00827139 0.00769619]
1.0
0.08981924986240757
0.049593456377752296
0.03410000609759861
0.02594880605802182
0.021018571283703148
0.01758670960716616
0.01516782448607984
0.013355435799743553
0.011895721348228538
0.010733260891365039
0.009766674332990784
0.008958380274750754
0.008271391878372591
0.007696190401970933



1.0
0.08981924986240757
0.5521473008706217
0.6875908353283464
0.7609619184158793
0.8100014789391613
0.8367224094247596
0.8624594836034204
0.8805109666188718
0.8907025968000951
0.9022791117214083
0.9099447438986712
0.9172395811837711
0.923313325031039
0.930458925793898


In [ ]:
# Plot network
def plot_network(P, figname, source=None, target=None):
    """
    Network plots
    =============
    
    We demonstrate different kinds of network plots based on :meth:`plots.Network <deeptime.plots.Network>`.
    In particular:
    
        * plotting a Markov state model where the state sizes depend on the stationary distribution and edges are scaled
          according to jump probabilities (:meth:`deeptime.plots.plot_markov_model`)
        * plotting the gross flux, in accordance to edge widths and colored according to the forward committor
          (:meth:`deeptime.plots.Network`).
    """
    import matplotlib as mpl
    import matplotlib.pyplot as plt
    import networkx as nx
    
    from mpl_toolkits.axes_grid1 import make_axes_locatable
    
    from deeptime.markov.msm import MarkovStateModel
    from deeptime.plots import plot_markov_model, Network, plot_flux
    
    if source is None:
        source = 0
    elif target is None:
        target = len(P)-1

    f1, axes1 = plt.subplots(figsize=(16, 12))
    axes1.set_aspect('equal')
    f2, axes2 = plt.subplots(figsize=(16, 12))
    axes2.set_aspect('equal')
    f3, axes3 = plt.subplots(figsize=(16, 12))
    axes3.set_aspect('equal')

    ax = axes1
    ax.set_title('Plotting the Markov model')
    plot_markov_model(P, ax=ax)
    
    ax = axes2
    ax.set_title('Plotting the gross flux')
    flux = MarkovStateModel(P).reactive_flux(source_states=source,
                                             target_states=target)
    positions = nx.multipartite_layout(nx.from_numpy_array(flux.gross_flux))
    #cmap = mpl.cm.get_cmap('coolwarm')
    cmap = mpl.colormaps['coolwarm'] #m.get_cmap('coolwarm')
    network = Network(flux.gross_flux, positions, edge_curvature=2.,
                      state_colors=flux.forward_committor, cmap=cmap)
    network.plot(ax=ax)
    norm = mpl.colors.Normalize(vmin=np.min(flux.forward_committor), vmax=np.max(flux.forward_committor))
    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="5%", pad=0.05)
    f1.colorbar(mpl.cm.ScalarMappable(norm, cmap), cax=cax)
    
    ax = axes3
    ax.set_title('Plotting the net flux')
    ax.get_yaxis().set_visible(False)
    plot_flux(flux, attribute_to_plot='net_flux', ax=ax)
    
    plt.show()
    # f.savefig(figname)

In [ ]:
A = [0]
B = [len(M_valid)-1]

plot_network(M_valid, "fig_try-plot-network-M.png", source=A, target=B)
# from deeptime.plots import plot_markov_model, Network, plot_flux
# plot_markov_model(M)

# Error analysis (recursive block analysis)

In [23]:
from tistools import block_error_analysis_staple
import logging
import sys
from datetime import datetime
from contextlib import redirect_stdout, redirect_stderr

# Create a log file with timestamp
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
log_filename = f"block_error_analysis_{timestamp}.log"

# Configure logging to file
file_handler = logging.FileHandler(log_filename, mode='w')
formatter = logging.Formatter('%(message)s')
file_handler.setFormatter(formatter)

# Create logger
log = logging.getLogger()
log.setLevel(logging.INFO)
log.handlers = [file_handler]  # Replace any existing handlers

# Write initial message to log file only
log.info(f"Starting block error analysis at {timestamp}")

# Open the log file for capturing all output
with open(log_filename, 'a') as log_file, redirect_stdout(log_file), redirect_stderr(log_file):
    # Run the block error analysis for StapleTIS
    block_error_analysis_staple(pathensembles, interfaces, 1, pl=False)
    
    # Calculate REPPTIS probabilities for comparison
    repptisploc = []
    for i, pe in enumerate(pathensembles):
        # REPPTIS p_loc
        repptisploc.append(get_local_probs(pe, tr=False))

    _, _, reppfull = get_global_probs_from_dict(repptisploc)
    
    # Write REPPTIS results to log file
    print("\nREPPTIS global crossing probabilities:")
    for i, p in enumerate(reppfull):
        print(f"Interface {i}: {p:.8f}")

# Log file path is the only output to notebook
log.info(f"Analysis complete - results saved to {log_filename}")


qt.qpa.xcb: QXcbConnection: XCB error: 148 (Unknown), sequence: 29965, resource id: 0, major code: 140 (Unknown), minor code: 20


In [ ]:
# PyRETIS code for block error analysis
 
def block_error(data, maxblock=None, blockskip=1):
    """
    Perform block error analysis to estimate the standard deviation in the input data.

    Parameters
    ----------
    data : numpy.array
        The data to analyze.
    maxblock : int, optional
        Maximum block length to consider. Defaults to half the length of the input data.
    blockskip : int, optional
        Skip factor for block lengths. Defaults to 1 (all block lengths considered).

    Returns
    -------
    blocklen : numpy.array
        Array of block lengths considered.
    block_avg : numpy.array
        Block averages as a function of block length.
    block_err : numpy.array
        Standard error estimates as a function of block length.
    block_err_avg : float
        Average error estimate for block lengths greater than maxblock//2.
    """
    n = len(data)
    maxblock = min(maxblock or n // 2, n // 2)
    
    blocklen = np.arange(1, maxblock + 1, blockskip, dtype=np.int_)
    n_blocks = len(blocklen)
    
    block = np.zeros(n_blocks)
    nblock = np.zeros(n_blocks)
    block_avg = np.zeros(n_blocks)
    block_var = np.zeros(n_blocks)

    for i, val in enumerate(data):
        block += val
        full_blocks = (i + 1) % blocklen == 0
        block[full_blocks] /= blocklen[full_blocks]
        nblock[full_blocks] += 1
        deltas = block[full_blocks] - block_avg[full_blocks]
        block_avg[full_blocks] += deltas / nblock[full_blocks]
        block_var[full_blocks] += deltas * (block[full_blocks] - block_avg[full_blocks])
        block[full_blocks] = 0.0

    block_var /= (nblock - 1)
    block_err = np.sqrt(block_var / nblock)
    
    large_blocks = blocklen > maxblock // 2
    block_err_avg = np.mean(block_err[large_blocks])
    
    return blocklen, block_avg, block_err, block_err_avg, maxblock, n//maxblock


def block_error_corr(data, maxblock=None, blockskip=1):
    """
    Run block error analysis and calculate correlation length estimates.

    Parameters
    ----------
    data : numpy.array
        Data to analyze.
    maxblock : int, optional
        Maximum block length to consider. Defaults to half the length of the input data.
    blockskip : int, optional
        Skip factor for block lengths. Defaults to 1 (all block lengths considered).

    Returns
    -------
    blen : numpy.array
        Block lengths considered.
    berr : numpy.array
        Error estimates as a function of block length.
    berr_avg : float
        Average error estimate for blocks with length > maxblock // 2.
    rel_err : numpy.array
        Relative error normalized by the overall average as a function of block length.
    avg_rel_err : float
        Average relative error for blocks with length > maxblock // 2.
    ncor : numpy.array
        Estimated correlation length as a function of block length.
    avg_ncor : float
        Average correlation length for blocks with length > maxblock // 2.
    """
    blen, bavg, berr, berr_avg, max_block_size, min_block_number = block_error(data, maxblock=maxblock, blockskip=blockskip)
    rel_err = berr / abs(bavg[0])
    avg_rel_err = berr_avg / abs(bavg[0])
    ncor = (berr / berr[0])**2
    avg_ncor = (berr_avg / berr[0])**2
    
    return blen, berr, berr_avg, rel_err, avg_rel_err, ncor, avg_ncor, max_block_size, min_block_number

def pathensembles_nskip(obj, nskip):
    keys = [
        'cyclenumbers', 'flags', 'generation', 'lambmaxs', 'lambmins',
        'lengths', 'lmrs', 'newpathnumbers', 'pathnumbers',
        'shootlinks', 'weights', 'dirs', 'istar_idx']
    for key in keys:
        attr = getattr(obj, key)
        setattr(obj, key, attr[:nskip])

In [ ]:
%%capture
from datetime import datetime
import copy

start_cyc = 1
n_cycle = 100000
nstep = 1

ploc_MSM_stored = []
ploc_repptis_stored = []
# This loops over the npy file and calculates tau from cycle 100 every 10 cycles
for nskip in range(start_cyc, n_cycle, nstep):
    pathensemblesi = copy.deepcopy(pathensembles)
    for i, pe in enumerate(pathensemblesi):
        pathensembles_nskip(pe,nskip)
    # Analysis output is saved to the data dictionary.
    data = {}
    for i, pe in enumerate(pathensemblesi):
        if i == 0:
            data[i] = {}
            continue  #  [0-] is not used for Pcross calculations
        
        # Classify the paths according to their path type.
        pathtypes = ("LML", "LMR", "RML", "RMR")
        pathtype_cycles = {}
        for ptype in pathtypes:
            pathtype_cycles[ptype] = unwrap_by_weight(
                    (pe.lmrs == ptype).astype(int), pe.weights)
        
        data[i] = {}
        plocfull = get_local_probs(pe, tr=False)
        data[i]["full"] = {}
        for ptype in pathtypes:
            data[i]["full"][ptype] = plocfull[ptype]

    psfull = []
    for i in range(1, len(pathensemblesi)):   # do not use the 0- ensemble
        psfull.append({"LMR": data[i]["full"]["LMR"], 
                "RML": data[i]["full"]["RML"], 
                "RMR": data[i]["full"]["RMR"],
                "LML": data[i]["full"]["LML"]})

    Pminfull, Pplusfull, Pcrossfull = get_global_probs_from_dict(psfull)

    ploc_repptis_stored.append(Pcrossfull)
    
    N = len(interfaces)
    NS = 2*N

    wi = compute_weight_matrices(pathensemblesi, interfaces, len(interfaces), True)
    pi, _ = get_transition_probzz(wi)
    # pi = get_transition_probs(wi)
    # pi = get_simple_probs(wi)
    M = construct_M_istar(pi, max(4, 2*len(interfaces)), len(interfaces))

    plocMSM = np.ones(len(interfaces))
    for lint in range(1, len(interfaces)):
        # Mi = M[:min(NS, 1+2*lint), :min(NS, 1+2*lint)]
        Mi = M[np.r_[0:2+lint, 1+N:N+lint, -1]]
        Mi = Mi[:, np.r_[0:2+lint, 1+N:N+lint+1]]
        Msum = M[np.r_[0:2+lint, 1+N:N+lint+1]]
        Mi[:, -1] = np.sum(Msum[:, N+lint:], axis=1)
        
        # wi2 = compute_weight_matrices(pathensemblesi[:lint+1], interfaces[:lint+1], len(interfaces), True)
        # pi2 = get_transition_probzz(wi2)
        # # pi = get_transition_probs(wi)
        # # pi = get_simple_probs(wi)
        # Mi2 = construct_M_istar(pi2, max(4, 2*len(interfaces[:lint+1])), len(interfaces[:lint+1]))

        # print(Mi == Mi2)

        z1, z2, y1, y2 = global_pcross_msm_star(Mi)
        plocMSM[lint] = y1[0][0]
    # print(f"plocs: ", plocMSM)

    pcrosslocMSM = np.empty(len(plocMSM))

    for i in range (len(pcrosslocMSM)):
        pcrosslocMSM[i] = plocMSM[i]/np.prod(pcrosslocMSM[:i])
    # print(pcrosslocMSM)

    ploc_MSM_stored.append(plocMSM)

    # for i,fol in enumerate(folders):
    #     set_tau_distrib(pathensemblesi[i])
    #     if True:
    #         set_tau_first_hit_M_distrib(pathensemblesi[i])

    # Compute taus for pathlength analysis
    timestamp = datetime.now().strftime("%H:%M:%S")
    print(f"{nskip:5d} cycles, Plocs {plocMSM}")

    # Not sure if we need this, need to check later
    del data
    del Mi, wi, pi, z1, z2, y1, y2,N, NS
    del Pcrossfull, Pminfull, Pplusfull
    del plocMSM, pcrosslocMSM

np.save('plocMSM_vs_cycle_interval_1_full.npy', ploc_MSM_stored)
np.save('plocREPPTIS_vs_cycle_interval_1_full.npy', ploc_repptis_stored)

In [ ]:
# Adapted AG, Jan 17, 2025

#----------------
# part Titus
#----------------

# SETTINGS

minblocks = 5 #the minimal number of blocks
filerunav = "plocMSM_vs_cycle_interval_1_full.npy"

# FUNCTIONS

def get_second_column(file):
    arr = []
    with open(file, "r") as f:
        for line in f:
            values = line.strip().split()
            arr.append(float(values[1]))
    return arr
 
def get_first_column(file):
    arr = []
    with open(file, "r") as f:
        for line in f:
            values = line.strip().split()
            arr.append(float(values[0]))
    return arr
 
def rec_blocks(r):
    # no longer used
    """Compute the vector b, which is ... """
    b = np.zeros(len(r))
    for i in range(len(r)):
        if i == 0:
            b[i] = r[i]
        else:
            b[i] = (i+1) * r[i] - i * r[i - 1]
    return b
 
def rec_blocks_from_runav(runav, n):
    # see paper Vervust et al. PyRETIS3, 2024
    # paper: select values k[j*m], indexing starts at 1
    # here: runav, python indexing, so start index n-1 (end of first block)
    # collect them in runav_red
    assert n>0   # block size
    runav_red = runav[n-1::n]
    nb = len(runav_red)  # number of blocks
 
    # array b with average of each block
    b = np.zeros(nb)
    for i in range(nb):
        if i == 0:
            b[i] = runav_red[i]
        else:
            b[i] = (i+1) * runav_red[i] - i * runav_red[i - 1]
    return b
 
def compute_absolute_error(runavfull, bestav, n):
    # compute average in each block
    assert n>0
    blocks = rec_blocks_from_runav(runavfull, n)
    # compute standard deviation between blocks
    sum_qudiff = np.sum((blocks-bestav)**2)
    nb = len(blocks)
    assert nb>1
    Aerr2 = sum_qudiff/(nb*(nb-1))
    Aerr = np.sqrt(Aerr2)  #esitimate of absolute error
    return Aerr
 
 
# GET STARTED
 
# runavfull = get_second_column(filerunav) #all the running average data in an array
runavfull = np.load(filerunav)
runavfull = runavfull[5:,:]
maxbll = int(len(runavfull)/minblocks) #maximum block length
bestav = runavfull[-1] #most accurate average we have
print("maximum block length = ", maxbll)
 
# loop over block size
sizes = np.arange(1,maxbll+1)
if len(np.shape(runavfull)) == 1:
    rel_errors = np.zeros(len(sizes)) if len(np.shape(runavfull)) == 1 else np.zeros((len(sizes), np.shape(runavfull)[1]))
    for i, n in enumerate(sizes):
        # n is block size
        Aerr = compute_absolute_error(runavfull, bestav, n)
        Rerr = Aerr/bestav
        rel_errors[i] = Rerr
    
    second_half = rel_errors[len(rel_errors)//2:]
    half_av_err = np.mean(second_half)
    print("estimated relative error=", half_av_err)
    Nstatineff=(half_av_err/rel_errors[0])**2
    print("statistical inefficiency=", Nstatineff)
    
    plt.figure()
    plt.plot(sizes, rel_errors)
    plt.axhline(y=half_av_err, color='r', linestyle='--')
    plt.xlabel('Block Length')
    plt.ylabel('Relative Error')
    plt.title('Error Analysis')
    plt.show()
    # plt.savefig("figure_titus.png")

elif len(np.shape(runavfull)) == 2:
    rel_errs = np.empty(len(interfaces))
    for loc in range(len(interfaces)):
        rel_errors = np.zeros(len(sizes))
        intf_i = runavfull[:,loc]
        bestav = intf_i[-1]
        for i, n in enumerate(sizes):
        # n is block size
            Aerr = compute_absolute_error(intf_i, bestav, n)
            Rerr = Aerr/bestav
            rel_errors[i] = Rerr

        second_half = rel_errors[len(rel_errors)//2:]
        half_av_err = np.mean(second_half)
        rel_errs[loc] = half_av_err
        print("estimated relative error=", half_av_err)
        Nstatineff=(half_av_err/rel_errors[0])**2
        print("statistical inefficiency=", Nstatineff)
        
        plt.figure()
        plt.plot(sizes, rel_errors)
        plt.axhline(y=half_av_err, color='r', linestyle='--')
        plt.xlabel('Block Length')
        plt.ylabel('Relative Error')
        if loc < len(interfaces)-1:
            plt.title('Error Analysis $p_{local}$'+f' - interface {loc}')
        else:
            plt.title('Error Analysis $P_{cross}$')
        plt.show()
        # plt.savefig("figure_titus.png")

maximum block length =  19998
estimated relative error= 0.0
statistical inefficiency= nan


/tmp/ipykernel_400959/1067094454.py:122: RuntimeWarning: invalid value encountered in scalar divide
  Nstatineff=(half_av_err/rel_errors[0])**2


estimated relative error= 0.035026263859068325
statistical inefficiency= 12.803962037331534
estimated relative error= 0.03629506752480279
statistical inefficiency= 12.30855799268715
estimated relative error= 0.03860426506193927
statistical inefficiency= 13.119834706021457
estimated relative error= 0.04187121021039022
statistical inefficiency= 14.386298466893177
estimated relative error= 0.043738990358359854
statistical inefficiency= 14.632355747315064
estimated relative error= 0.0496850196134735
statistical inefficiency= 16.65657467803505
estimated relative error= 0.07627598921717178
statistical inefficiency= 36.33504361711302
estimated relative error= 0.07892064974077292
statistical inefficiency= 38.587801289250514
estimated relative error= 0.08168128812169928
statistical inefficiency= 41.15697280835939
estimated relative error= 0.08358957475156441
statistical inefficiency= 42.79071205318213


In [ ]:
stored_values = np.load('plocREPPTIS_vs_cycle_interval_10.npy')

if len(np.shape(stored_values)) == 1:
    stored_values = stored_values[~np.isnan(stored_values)] # remove nans in the beginning
    blen, berr, berr_avg, rel_err, avg_rel_err, ncor, avg_ncor, max_block_size, min_block_number = block_error_corr(stored_values,10)
    print("=" * 60)
    print(indir[57:-9])
    print(f"Total Data Points: {len(stored_values)}, max block size: {max_block_size}, min block number: {min_block_number}")
    print(f"Average Relative Error for blocks > maxblock/2: {avg_rel_err * 100:.1f}%")
    print(f"Average Correlation Length for Large Blocks: {int(avg_ncor)}")
    plt.figure(figsize=(8, 6))
    plt.plot(rel_err, marker='o', linestyle='-', label = indir[57:-9])
    plt.xlabel("Block Size")
    plt.ylabel("Rlative Error")
    plt.title(f"Ave Rel Err (blocks > maxblock/2): {avg_rel_err * 100:.1f}%, Block interval 10 cycles")
    plt.grid(True)
    plt.legend()
    # plt.savefig("Block_Error_Tau.png", dpi=1000, bbox_inches='tight')
elif len(np.shape(stored_values)) == 2:
    rel_errs = np.empty(len(interfaces))
    for loc in range(1,len(interfaces)):
        intf_i = stored_values[:,loc]
        blen, berr, berr_avg, rel_err, avg_rel_err, ncor, avg_ncor, max_block_size, min_block_number = block_error_corr(intf_i[~np.isnan(intf_i)],1000)
        rel_errs[loc] = avg_rel_err

        print("=" * 60)
        print(indir[57:-9])
        print(f"Total Data Points: {len(stored_values)}, max block size: {max_block_size}, min block number: {min_block_number}")
        print(f"Average Relative Error for blocks > maxblock/2: {avg_rel_err * 100:.10f}%")
        print(f"Average Correlation Length for Large Blocks: {int(avg_ncor)}")
        plt.figure(figsize=(8, 6))
        plt.plot(rel_err, linestyle='-', label = indir[57:-9])
        plt.xlabel("Block Size")
        plt.ylabel("Rlative Error")
        plt.title(f"Ave Rel Err (blocks > maxblock/2): {avg_rel_err * 100:.1f}%, Block interval 10 cycles")
        plt.grid(True)
        plt.legend()
        # plt.savefig("Block_Error_Tau.png", dpi=1000, bbox_inches='tight')

# Bootstrap 👢 analysis

In [ ]:
from tistools import bootstrap_istar_analysis

In [ ]:
from tistools import find_closest_number_lte
def bootstrap_istar_analysis2(pathensembles, interfaces, nN=10, nB=1000):
    N = len(interfaces)
    NS = max(3, 2*len(interfaces))
    data = {}
    # for each pathensemble, we save the indices of accepted cycle numbers in a
    # dictionary, because we will use this a lot. We do not accept load cycles, 
    # so if a load cycle is sampled, we will just not use it. 
    pathcycle_ids = {}
    for i, pe in enumerate(pathensembles):
        loadmask = get_generation_mask(pe, "load")
        accmask = get_flag_mask(pe, "ACC")
        pathcycle_ids[i] = select_with_masks(pe.cyclenumbers,
                                             [accmask, ~loadmask])
    for Bcycle in np.arange((pathensembles[0].cyclenumbers)[-1]//nN,
                            (pathensembles[0].cyclenumbers)[-1],
                            ((pathensembles[0].cyclenumbers)[-1]//nN)):
        logger.info(f"Doing bootstrap analysis for cycle {Bcycle}")
        # We produce a list of the data for each timeslice
        ts_data = {}
        for j in range(nB):
            if j % 100 == 0:
                logger.info(f"Doing bootstrap sample {j}")
            # A. Select cycle numbers randomly within the timeslice [1, Bcycle],
            #    using replacement. We start from one to discard the initial
            #    load cycle.
            cycle_ids = np.random.choice(np.arange(start=1,stop=Bcycle), 
                                         Bcycle, replace=True)
            # Store the data for each pathensemble in a dictionary
            boot_data = {}
            boot_pes = []
            for i, pe in enumerate(pathensembles):
                if pe.in_zero_minus:
                    logger.info(f"Passing pathensemble {i} because this is "+\
                                f"the zero minus ensemble: {pe.name}")
                    pass
                # map the cycle numbers to the indices of accepted cycles
                boot_cycle_ids = find_closest_number_lte(cycle_ids,
                                                         pathcycle_ids[i])
                # sample the pathensemble at the given cycle indices
                boot_pes.append(pe.sample_pe(boot_cycle_ids))
                #boot_data[i]['pe'] = boot_pe
            # B. get the transition crossing probabilities
            boot_data['w_path'] = compute_weight_matrices(boot_pes, interfaces)
            boot_data['p'], _ = get_transition_probs_weights(boot_data['w_path'])
            # C. Calculate the global crossing probabilities 
            Mj = construct_M_istar(boot_data['p'], NS, N)
            z1, z2, y1, y2 = global_pcross_msm_star(Mj)
            boot_data['z1'] = z1
            boot_data['z2'] = z2
            boot_data['y1'] = y1
            boot_data['y2'] = y2
            ts_data[j] = boot_data
        # save the boot_data for this timeslice 
        data[Bcycle] = {}
        data[Bcycle]['data'] = ts_data
        # D. Calculate the mean and std of the local crossing probabilities for
        #    each pathensemble, and the mean and std of the global crossing for 
        #    each bootstrap sample.
        ts_stats = {}
        # first the local crossing probabilities
        for attr in ['p', 'z1', 'z2', 'y1', 'y2']:
            ts_stats[attr] = {}
            ts_stats[attr]['mean'] = \
                np.mean(np.array([ts_data[j][attr]
                                  for j in ts_data.keys()]),axis=0)
            ts_stats[attr]['std'] = \
                np.std(np.array([ts_data[j][attr]
                                 for j in ts_data.keys()]),axis=0)
            
        data[Bcycle]['stats'] = ts_stats

    return data

In [ ]:
bs_data = bootstrap_istar_analysis2(pathensembles, interfaces)

print(bs_data)

# Collecting times

In [ ]:
# Additional information
#==================================
# Average path lengths per ensemble for each path type
print(indir[-20:])
pathtypes = ("LML", "LMR", "RMR", "RML", "LM*", "*M*", "***", "RM*", "L**", "**R", "R**")

print("=" * 80)
print("AVERAGE PATH LENGTHS BY ENSEMBLE AND PATH TYPE")
print("=" * 80)

for i, pe in enumerate(pathensembles):
    print(f"\nEnsemble {i} ({pe.name}):")
    print("-" * 50)
    
    for ptype in pathtypes:
        mask = (pe.lmrs == ptype)
        if np.any(mask):
            lengths = pe.lengths[mask]
            avg_length = np.mean(lengths)
            count = np.sum(mask)
            print(f"  {ptype:4s}: {avg_length:8.2f} (n={count:4d})")
        else:
            print(f"  {ptype:4s}: {0:8.2f} (n={0:4d})")

In [ ]:
def collect_tau(pathensembles, data):
    # pathensembles -- list of pathensemble instances
    
    print("Collect tau")
    
    # average path lengths
    taumm = np.zeros(len(pathensembles))
    taump = np.zeros(len(pathensembles))
    taupm = np.zeros(len(pathensembles))
    taupp = np.zeros(len(pathensembles))
    
    # for [1+-] and higher (i>=2)
    for i in range(2,len(pathensembles)):
        print("ensemble", i, pathensembles[i].name)
        taumm[i] = pathensembles[i].tauavg['LML']-2
        taump[i] = pathensembles[i].tauavg['LMR']-2
        taupm[i] = pathensembles[i].tauavg['RML']-2
        taupp[i] = pathensembles[i].tauavg['RMR']-2

    # for [0-] (i=0)
    print("ensemble", 0, pathensembles[0].name)
    if pe.has_zero_minus_one:
        # TODO pieces missing
        taumm[0] = pathensembles[0].tauavg['LML']-2
        taump[0] = pathensembles[0].tauavg['LMR']-2
        taupm[0] = pathensembles[0].tauavg['RML']-2
        taupp[0] = pathensembles[0].tauavg['RMR']-2
    else:
        taupp[0] = pathensembles[0].tauavg['RMR']-2

    # for [0+-] (i=1)
    print("ensemble", 1, pathensembles[1].name)
    taumm[1] = data[1]["pathlengths"]["LML"]["mean"] - 2
    taump[1] = data[1]["pathlengths"]["LMR"]["mean"] - 2
    taupm[1] = data[1]["pathlengths"]["RML"]["mean"] - 2
    #taupp[1] = data[1]["pathlengths"]["RMR"]["mean"] - 2

    return taumm, taump, taupm, taupp

# this is the same:
# 1) after:
#   data[2]["pathlengths"] = pathlength_distr(upe)  # use correct upe!
#   This gives the whole distrib, mean, std, etc
#   print(data[2]["pathlengths"]["RMR"]["mean"])
# 2) after:
#   set_tau_distrib(pathensembles[2])
#   print(pathensembles[2].tauavg['RMR'])

# TODO for [0-]
# likely not okay yet, what about L*L etc??????
# There are paths missing TODO!!!!!!!! when lambda-1

In [ ]:
# TODO fix +-1 issues!!!!!!
# TODO tau1 is not fool proof if you have too many phase points!!

def collect_tau1(pathensembles, data):
    # average path lengths, but only the part before the 1st crossing
    #---------------------------
    print("Collect tau1")
    taumm1 = np.zeros(len(pathensembles))
    taump1 = np.zeros(len(pathensembles))
    taupm1 = np.zeros(len(pathensembles))
    taupp1 = np.zeros(len(pathensembles))
    
    # for [1+-] and higher (i>=2)
    for i in range(2,len(pathensembles)):
        taumm1[i] = pathensembles[i].tau1avg['LML'] - 1
        taump1[i] = pathensembles[i].tau1avg['LMR'] - 1
        taupm1[i] = pathensembles[i].tau1avg['RML'] - 1
        taupp1[i] = pathensembles[i].tau1avg['RMR'] - 1
    # for [0-] (i=0) -> just 0
    # for [0+-] (i=1) LML -> just 0
    # for [0+-] (i=1) LMR -> just 0
    # for [0+-] (i=1) RML
    taupm1[1] = data[1]["pathlengths"]["RML"]["mean"] - 2
    
    return taumm1, taump1, taupm1, taupp1

def collect_tau2(pathensembles, data):
    # average path lengths, but only the part after the last crossing
    #---------------------------
    print("Collect tau2")
    taumm2 = np.zeros(len(pathensembles))
    taump2 = np.zeros(len(pathensembles))
    taupm2 = np.zeros(len(pathensembles))
    taupp2 = np.zeros(len(pathensembles))
    
    # for [1+-] and higher (i>=2)
    for i in range(2,len(pathensembles)):
        taumm2[i] = pathensembles[i].tau2avg['LML'] - 1
        taump2[i] = pathensembles[i].tau2avg['LMR'] - 1
        taupm2[i] = pathensembles[i].tau2avg['RML'] - 1
        taupp2[i] = pathensembles[i].tau2avg['RMR'] - 1
    # for [0-] (i=0) -> just 0
    # for [0+-] (i=1) LML -> just 0
    # for [0+-] (i=1) LMR
    taump2[1] = data[1]["pathlengths"]["LMR"]["mean"] - 2
    # for [0+-] (i=1) RML -> just 0
    
    return taumm2, taump2, taupm2, taupp2

def collect_taum(pathensembles, data):
    # average path lengths, but only the part between first/last crossing
    #---------------------------
    print("Collect taum")
    taumm_m = np.zeros(len(pathensembles))
    taump_m = np.zeros(len(pathensembles))
    taupm_m = np.zeros(len(pathensembles))
    taupp_m = np.zeros(len(pathensembles))
    
    # for [1+-] and higher (i>=2)
    for i in range(2,len(pathensembles)):
        #print("ensemble", i, pathensembles[i].name)
        taumm_m[i] = pathensembles[i].tauavg['LML'] \
                   - pathensembles[i].tau1avg['LML'] \
                   - pathensembles[i].tau2avg['LML']
        taump_m[i] = pathensembles[i].tauavg['LMR'] \
                   - pathensembles[i].tau1avg['LMR'] \
                   - pathensembles[i].tau2avg['LMR']
        taupm_m[i] = pathensembles[i].tauavg['RML'] \
                   - pathensembles[i].tau1avg['RML'] \
                   - pathensembles[i].tau2avg['RML']
        taupp_m[i] = pathensembles[i].tauavg['RMR'] \
                   - pathensembles[i].tau1avg['RMR'] \
                   - pathensembles[i].tau2avg['RMR']

    # for [0-] (i=0)
    if pe.has_zero_minus_one:
        # TODO there are more paths!!!
        taumm_m[0] = pathensembles[0].tauavg['LML']-2
        taump_m[0] = pathensembles[0].tauavg['LMR']-2
        taupm_m[0] = pathensembles[0].tauavg['RML']-2
        taupp_m[0] = pathensembles[0].tauavg['RMR']-2
    else:
        taupp_m[0] = pathensembles[0].tauavg['RMR']-2

    # for [0+-] (i=1) LML
    taumm_m[1] = data[1]["pathlengths"]["LML"]["mean"] - 2
    # for [0+-] (i=1) LMR -> just 0
    # for [0+-] (i=1) RML -> just 0

    return taumm_m, taump_m, taupm_m, taupp_m


In [ ]:
def print_all_tau(pathensembles, taumm, taump, taupm, taupp):
    # print all tau
    print(f"                  mm            mp            pm            pp")
    for i in range(len(pathensembles)):
        print(f"{i} {pathensembles[i].name[-3:]}  {taumm[i]:13.1f} {taump[i]:13.1f} {taupm[i]:13.1f} {taupp[i]:13.1f}")

In [ ]:
taumm, taump, taupm, taupp = collect_tau(pathensembles, data)
taumm1, taump1, taupm1, taupp1 = collect_tau1(pathensembles, data)
taumm2, taump2, taupm2, taupp2 = collect_tau2(pathensembles, data)
taumm_m, taump_m, taupm_m, taupp_m = collect_taum(pathensembles, data)

In [ ]:
print("tau")
print_all_tau(pathensembles, taumm, taump, taupm, taupp)
print("\ntau1")
print_all_tau(pathensembles, taumm1, taump1, taupm1, taupp1)
print("\ntau_m")
print_all_tau(pathensembles, taumm_m, taump_m, taupm_m, taupp_m)
print("\ntau2")
print_all_tau(pathensembles, taumm2, taump2, taupm2, taupp2)

In [ ]:
def construct_tau_vector(N, NS, taumm, taump, taupm, taupp):
    assert N>=4
    assert NS==4*N-5
    assert len(taumm) == N
    assert len(taump) == N
    assert len(taupm) == N
    assert len(taupp) == N
    # unravel the values into one vector
    tau = np.zeros(NS)
    # [0-]
    tau[0] = taupp[0]
    # [0+-]
    tau[1] = taumm[1]
    tau[2] = taump[1]
    tau[3] = taupm[1]
    # [1+-] etc
    for i in range(1,N-2):
        tau[4*i]   = taumm[i+1]
        tau[4*i+1] = taump[i+1]
        tau[4*i+2] = taupm[i+1]
        tau[4*i+3] = taupp[i+1]
    # [(N-2)^(-1)]
    tau[-3] = taumm[-1]
    tau[-2] = taump[-1]
    # B
    tau[-1] = 0.   # whatever
    return tau

In [ ]:
tau  = construct_tau_vector(N, NS, taumm, taump, taupm, taupp)
tau1 = construct_tau_vector(N, NS, taumm1, taump1, taupm1, taupp1)
taum = construct_tau_vector(N, NS, taumm_m, taump_m, taupm_m, taupp_m)
tau2 = construct_tau_vector(N, NS, taumm2, taump2, taupm2, taupp2)
tau_m = tau-tau1-tau2  # yes, this is the same thing

print("tau")
print(tau)
print("\n")
print("tau1")
print(tau1)
print("taum")
print(taum)
print("tau2")
print(tau2)

print("\n")
print("tau = tau1+taum+tau2 => difference is", np.sum((tau-tau1-taum-tau2)**2))

# Compute tau for [0+]

In [ ]:
g1, g2, h1, h2 = vector_G(M_valid, tau1, tau_m, tau2) #, doprint=True)
print("G")
print_vector(g1, labels1)
print_vector(g2, labels2)
print("H")
print_vector(h1, labels1)
print_vector(h2, labels2)
print("interesting")
print(h1[0])

In [ ]:
print(h1[0])

# Flux

In [ ]:
flux = 1/(tau[0]+h1[0])
# dt = 0.0002
# dt = 0.00002
dt = 0.01
flux
print(flux/dt, "1/time")

## MSM insights

In [ ]:
import deeptime.markov as dpt

msm = dpt.msm.MarkovStateModel(M_valid)
print(msm)

tt = dpt.pcca(M_valid, 2)